package com.neteast.rmp.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neteast.rmp.dao.RptColumnMetaDAO;
import com.neteast.rmp.dao.domain.RptColumnMeta;
import com.neteast.rmp.dao.domain.RptColumnMetaExample;
import com.neteast.rmp.dao.ibatis.ext.BaseSqlMapClientDaoSupport;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import com.seraph.bi.suite.support.domain.pagination.PageObject;

@Repository
public class RptColumnMetaDAOImpl extends BaseSqlMapClientDaoSupport implements RptColumnMetaDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public RptColumnMetaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer insert(RptColumnMeta record) {
        Object newKey = getSqlMapClientTemplate().insert("rpt_column_meta.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKey(RptColumnMeta record) {
        int rows = getSqlMapClientTemplate().update("rpt_column_meta.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeySelective(RptColumnMeta record) {
        int rows = getSqlMapClientTemplate().update("rpt_column_meta.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(RptColumnMetaExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("rpt_column_meta.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(RptColumnMetaExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public RptColumnMeta selectByPrimaryKey(Integer id) {
        RptColumnMeta key = new RptColumnMeta();
        key.setId(id);
        RptColumnMeta record = (RptColumnMeta) getSqlMapClientTemplate().queryForObject("rpt_column_meta.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByExample(RptColumnMetaExample example) {
        int rows = getSqlMapClientTemplate().delete("rpt_column_meta.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        RptColumnMeta key = new RptColumnMeta();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("rpt_column_meta.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getIDExampleParms(RptColumnMetaExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case RptColumnMetaExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NULL", "Y");
            } else {
                parms.put("AND_ID_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_NULL", "Y");
            } else {
                parms.put("AND_ID_NOT_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_EQUALS", "Y");
            } else {
                parms.put("AND_ID_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ID_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GT", "Y");
            } else {
                parms.put("AND_ID_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GE", "Y");
            } else {
                parms.put("AND_ID_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LT", "Y");
            } else {
                parms.put("AND_ID_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LE", "Y");
            } else {
                parms.put("AND_ID_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getRPT_CODEExampleParms(RptColumnMetaExample example) {
        Map parms = new HashMap();
        switch (example.getRptCode_Indicator()) {
        case RptColumnMetaExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_NULL", "Y");
            } else {
                parms.put("AND_RPT_CODE_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_NOT_NULL", "Y");
            } else {
                parms.put("AND_RPT_CODE_NOT_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_EQUALS", "Y");
            } else {
                parms.put("AND_RPT_CODE_EQUALS", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_RPT_CODE_NOT_EQUALS", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_GT", "Y");
            } else {
                parms.put("AND_RPT_CODE_GT", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_GE", "Y");
            } else {
                parms.put("AND_RPT_CODE_GE", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_LT", "Y");
            } else {
                parms.put("AND_RPT_CODE_LT", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_LE", "Y");
            } else {
                parms.put("AND_RPT_CODE_LE", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptColumnMetaExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_LIKE", "Y");
            } else {
                parms.put("AND_RPT_CODE_LIKE", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getCOL_NAMEExampleParms(RptColumnMetaExample example) {
        Map parms = new HashMap();
        switch (example.getColName_Indicator()) {
        case RptColumnMetaExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NAME_NULL", "Y");
            } else {
                parms.put("AND_COL_NAME_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NAME_NOT_NULL", "Y");
            } else {
                parms.put("AND_COL_NAME_NOT_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NAME_EQUALS", "Y");
            } else {
                parms.put("AND_COL_NAME_EQUALS", "Y");
            }
            parms.put("colName", example.getColName());
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NAME_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_COL_NAME_NOT_EQUALS", "Y");
            }
            parms.put("colName", example.getColName());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NAME_GT", "Y");
            } else {
                parms.put("AND_COL_NAME_GT", "Y");
            }
            parms.put("colName", example.getColName());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NAME_GE", "Y");
            } else {
                parms.put("AND_COL_NAME_GE", "Y");
            }
            parms.put("colName", example.getColName());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NAME_LT", "Y");
            } else {
                parms.put("AND_COL_NAME_LT", "Y");
            }
            parms.put("colName", example.getColName());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NAME_LE", "Y");
            } else {
                parms.put("AND_COL_NAME_LE", "Y");
            }
            parms.put("colName", example.getColName());
            break;
        case RptColumnMetaExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NAME_LIKE", "Y");
            } else {
                parms.put("AND_COL_NAME_LIKE", "Y");
            }
            parms.put("colName", example.getColName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getCOL_ALIASExampleParms(RptColumnMetaExample example) {
        Map parms = new HashMap();
        switch (example.getColAlias_Indicator()) {
        case RptColumnMetaExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_ALIAS_NULL", "Y");
            } else {
                parms.put("AND_COL_ALIAS_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_ALIAS_NOT_NULL", "Y");
            } else {
                parms.put("AND_COL_ALIAS_NOT_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_ALIAS_EQUALS", "Y");
            } else {
                parms.put("AND_COL_ALIAS_EQUALS", "Y");
            }
            parms.put("colAlias", example.getColAlias());
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_ALIAS_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_COL_ALIAS_NOT_EQUALS", "Y");
            }
            parms.put("colAlias", example.getColAlias());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_ALIAS_GT", "Y");
            } else {
                parms.put("AND_COL_ALIAS_GT", "Y");
            }
            parms.put("colAlias", example.getColAlias());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_ALIAS_GE", "Y");
            } else {
                parms.put("AND_COL_ALIAS_GE", "Y");
            }
            parms.put("colAlias", example.getColAlias());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_ALIAS_LT", "Y");
            } else {
                parms.put("AND_COL_ALIAS_LT", "Y");
            }
            parms.put("colAlias", example.getColAlias());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_ALIAS_LE", "Y");
            } else {
                parms.put("AND_COL_ALIAS_LE", "Y");
            }
            parms.put("colAlias", example.getColAlias());
            break;
        case RptColumnMetaExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_ALIAS_LIKE", "Y");
            } else {
                parms.put("AND_COL_ALIAS_LIKE", "Y");
            }
            parms.put("colAlias", example.getColAlias());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getCOL_INDEXExampleParms(RptColumnMetaExample example) {
        Map parms = new HashMap();
        switch (example.getColIndex_Indicator()) {
        case RptColumnMetaExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_INDEX_NULL", "Y");
            } else {
                parms.put("AND_COL_INDEX_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_INDEX_NOT_NULL", "Y");
            } else {
                parms.put("AND_COL_INDEX_NOT_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_INDEX_EQUALS", "Y");
            } else {
                parms.put("AND_COL_INDEX_EQUALS", "Y");
            }
            parms.put("colIndex", example.getColIndex());
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_INDEX_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_COL_INDEX_NOT_EQUALS", "Y");
            }
            parms.put("colIndex", example.getColIndex());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_INDEX_GT", "Y");
            } else {
                parms.put("AND_COL_INDEX_GT", "Y");
            }
            parms.put("colIndex", example.getColIndex());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_INDEX_GE", "Y");
            } else {
                parms.put("AND_COL_INDEX_GE", "Y");
            }
            parms.put("colIndex", example.getColIndex());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_INDEX_LT", "Y");
            } else {
                parms.put("AND_COL_INDEX_LT", "Y");
            }
            parms.put("colIndex", example.getColIndex());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_INDEX_LE", "Y");
            } else {
                parms.put("AND_COL_INDEX_LE", "Y");
            }
            parms.put("colIndex", example.getColIndex());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getCOL_TYPEExampleParms(RptColumnMetaExample example) {
        Map parms = new HashMap();
        switch (example.getColType_Indicator()) {
        case RptColumnMetaExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_TYPE_NULL", "Y");
            } else {
                parms.put("AND_COL_TYPE_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_TYPE_NOT_NULL", "Y");
            } else {
                parms.put("AND_COL_TYPE_NOT_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_TYPE_EQUALS", "Y");
            } else {
                parms.put("AND_COL_TYPE_EQUALS", "Y");
            }
            parms.put("colType", example.getColType());
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_TYPE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_COL_TYPE_NOT_EQUALS", "Y");
            }
            parms.put("colType", example.getColType());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_TYPE_GT", "Y");
            } else {
                parms.put("AND_COL_TYPE_GT", "Y");
            }
            parms.put("colType", example.getColType());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_TYPE_GE", "Y");
            } else {
                parms.put("AND_COL_TYPE_GE", "Y");
            }
            parms.put("colType", example.getColType());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_TYPE_LT", "Y");
            } else {
                parms.put("AND_COL_TYPE_LT", "Y");
            }
            parms.put("colType", example.getColType());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_TYPE_LE", "Y");
            } else {
                parms.put("AND_COL_TYPE_LE", "Y");
            }
            parms.put("colType", example.getColType());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getTOTAL_ENABLEExampleParms(RptColumnMetaExample example) {
        Map parms = new HashMap();
        switch (example.getTotalEnable_Indicator()) {
        case RptColumnMetaExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TOTAL_ENABLE_NULL", "Y");
            } else {
                parms.put("AND_TOTAL_ENABLE_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TOTAL_ENABLE_NOT_NULL", "Y");
            } else {
                parms.put("AND_TOTAL_ENABLE_NOT_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TOTAL_ENABLE_EQUALS", "Y");
            } else {
                parms.put("AND_TOTAL_ENABLE_EQUALS", "Y");
            }
            parms.put("totalEnable", example.getTotalEnable());
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TOTAL_ENABLE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_TOTAL_ENABLE_NOT_EQUALS", "Y");
            }
            parms.put("totalEnable", example.getTotalEnable());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TOTAL_ENABLE_GT", "Y");
            } else {
                parms.put("AND_TOTAL_ENABLE_GT", "Y");
            }
            parms.put("totalEnable", example.getTotalEnable());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TOTAL_ENABLE_GE", "Y");
            } else {
                parms.put("AND_TOTAL_ENABLE_GE", "Y");
            }
            parms.put("totalEnable", example.getTotalEnable());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TOTAL_ENABLE_LT", "Y");
            } else {
                parms.put("AND_TOTAL_ENABLE_LT", "Y");
            }
            parms.put("totalEnable", example.getTotalEnable());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TOTAL_ENABLE_LE", "Y");
            } else {
                parms.put("AND_TOTAL_ENABLE_LE", "Y");
            }
            parms.put("totalEnable", example.getTotalEnable());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getSUB_TOTAL_ENABLEExampleParms(RptColumnMetaExample example) {
        Map parms = new HashMap();
        switch (example.getSubTotalEnable_Indicator()) {
        case RptColumnMetaExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SUB_TOTAL_ENABLE_NULL", "Y");
            } else {
                parms.put("AND_SUB_TOTAL_ENABLE_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SUB_TOTAL_ENABLE_NOT_NULL", "Y");
            } else {
                parms.put("AND_SUB_TOTAL_ENABLE_NOT_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SUB_TOTAL_ENABLE_EQUALS", "Y");
            } else {
                parms.put("AND_SUB_TOTAL_ENABLE_EQUALS", "Y");
            }
            parms.put("subTotalEnable", example.getSubTotalEnable());
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SUB_TOTAL_ENABLE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_SUB_TOTAL_ENABLE_NOT_EQUALS", "Y");
            }
            parms.put("subTotalEnable", example.getSubTotalEnable());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SUB_TOTAL_ENABLE_GT", "Y");
            } else {
                parms.put("AND_SUB_TOTAL_ENABLE_GT", "Y");
            }
            parms.put("subTotalEnable", example.getSubTotalEnable());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SUB_TOTAL_ENABLE_GE", "Y");
            } else {
                parms.put("AND_SUB_TOTAL_ENABLE_GE", "Y");
            }
            parms.put("subTotalEnable", example.getSubTotalEnable());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SUB_TOTAL_ENABLE_LT", "Y");
            } else {
                parms.put("AND_SUB_TOTAL_ENABLE_LT", "Y");
            }
            parms.put("subTotalEnable", example.getSubTotalEnable());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SUB_TOTAL_ENABLE_LE", "Y");
            } else {
                parms.put("AND_SUB_TOTAL_ENABLE_LE", "Y");
            }
            parms.put("subTotalEnable", example.getSubTotalEnable());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getVISIBLEExampleParms(RptColumnMetaExample example) {
        Map parms = new HashMap();
        switch (example.getVisible_Indicator()) {
        case RptColumnMetaExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_VISIBLE_NULL", "Y");
            } else {
                parms.put("AND_VISIBLE_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_VISIBLE_NOT_NULL", "Y");
            } else {
                parms.put("AND_VISIBLE_NOT_NULL", "Y");
            }
            break;
        case RptColumnMetaExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_VISIBLE_EQUALS", "Y");
            } else {
                parms.put("AND_VISIBLE_EQUALS", "Y");
            }
            parms.put("visible", example.getVisible());
            break;
        case RptColumnMetaExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_VISIBLE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_VISIBLE_NOT_EQUALS", "Y");
            }
            parms.put("visible", example.getVisible());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_VISIBLE_GT", "Y");
            } else {
                parms.put("AND_VISIBLE_GT", "Y");
            }
            parms.put("visible", example.getVisible());
            break;
        case RptColumnMetaExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_VISIBLE_GE", "Y");
            } else {
                parms.put("AND_VISIBLE_GE", "Y");
            }
            parms.put("visible", example.getVisible());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_VISIBLE_LT", "Y");
            } else {
                parms.put("AND_VISIBLE_LT", "Y");
            }
            parms.put("visible", example.getVisible());
            break;
        case RptColumnMetaExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_VISIBLE_LE", "Y");
            } else {
                parms.put("AND_VISIBLE_LE", "Y");
            }
            parms.put("visible", example.getVisible());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getExampleParms(RptColumnMetaExample example) {
        Map parms = new HashMap();
        parms.putAll(getIDExampleParms(example));
        parms.putAll(getRPT_CODEExampleParms(example));
        parms.putAll(getCOL_NAMEExampleParms(example));
        parms.putAll(getCOL_ALIASExampleParms(example));
        parms.putAll(getCOL_INDEXExampleParms(example));
        parms.putAll(getCOL_TYPEExampleParms(example));
        parms.putAll(getTOTAL_ENABLEExampleParms(example));
        parms.putAll(getSUB_TOTAL_ENABLEExampleParms(example));
        parms.putAll(getVISIBLEExampleParms(example));
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int selectCountByExample(RptColumnMetaExample example) {
        Map parms = getExampleParms(example);
        int count = ((Integer)getSqlMapClientTemplate().queryForObject("rpt_column_meta.abatorgenerated_selectCountByExample", parms)).intValue();
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(RptColumnMetaExample example, int pageSize, int pageNum, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        PageBox pageBox = new PageBox();
        PageObject pageObject = new PageObject();
        pageObject.setPageSize(pageSize);
        pageObject.setPageIndex(pageNum);
        int itemAmount = selectCountByExample(example);
        pageObject.setItemAmount(itemAmount);
        List pageList = null;
        if (pageObject.getBeginIndex() <= pageObject.getItemAmount()) {
            pageList = (getSqlMapClientTemplate().queryForList("rpt_column_meta.abatorgenerated_selectByExample", parms, pageObject.getBeginIndex() - 1, pageSize));
        }
        pageBox.setPageObject(pageObject);
        pageBox.setPageList(pageList);
        return pageBox;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(RptColumnMetaExample example, int pageSize, int pageNum) {
        return selectByExampleWithPaging(example, pageSize, pageNum, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeyForCgs(RptColumnMeta record) {
        int rows = getSqlMapClientTemplate().update("rpt_column_meta.abatorgenerated_updateByPrimaryKeyForCgs", record);
        return rows;
    }
}