package com.neteast.rmp.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neteast.rmp.dao.RptTemplateDAO;
import com.neteast.rmp.dao.domain.RptTemplate;
import com.neteast.rmp.dao.domain.RptTemplateExample;
import com.neteast.rmp.dao.ibatis.ext.BaseSqlMapClientDaoSupport;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import com.seraph.bi.suite.support.domain.pagination.PageObject;

@Repository
public class RptTemplateDAOImpl extends BaseSqlMapClientDaoSupport implements RptTemplateDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public RptTemplateDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer insert(RptTemplate record) {
        Object newKey = getSqlMapClientTemplate().insert("rpt_template.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKey(RptTemplate record) {
        int rows = getSqlMapClientTemplate().update("rpt_template.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeySelective(RptTemplate record) {
        int rows = getSqlMapClientTemplate().update("rpt_template.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(RptTemplateExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("rpt_template.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(RptTemplateExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public RptTemplate selectByPrimaryKey(Integer id) {
        RptTemplate key = new RptTemplate();
        key.setId(id);
        RptTemplate record = (RptTemplate) getSqlMapClientTemplate().queryForObject("rpt_template.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByExample(RptTemplateExample example) {
        int rows = getSqlMapClientTemplate().delete("rpt_template.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        RptTemplate key = new RptTemplate();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("rpt_template.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getIDExampleParms(RptTemplateExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case RptTemplateExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NULL", "Y");
            } else {
                parms.put("AND_ID_NULL", "Y");
            }
            break;
        case RptTemplateExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_NULL", "Y");
            } else {
                parms.put("AND_ID_NOT_NULL", "Y");
            }
            break;
        case RptTemplateExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_EQUALS", "Y");
            } else {
                parms.put("AND_ID_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case RptTemplateExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ID_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case RptTemplateExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GT", "Y");
            } else {
                parms.put("AND_ID_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case RptTemplateExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GE", "Y");
            } else {
                parms.put("AND_ID_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case RptTemplateExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LT", "Y");
            } else {
                parms.put("AND_ID_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case RptTemplateExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LE", "Y");
            } else {
                parms.put("AND_ID_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getRPT_CODEExampleParms(RptTemplateExample example) {
        Map parms = new HashMap();
        switch (example.getRptCode_Indicator()) {
        case RptTemplateExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_NULL", "Y");
            } else {
                parms.put("AND_RPT_CODE_NULL", "Y");
            }
            break;
        case RptTemplateExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_NOT_NULL", "Y");
            } else {
                parms.put("AND_RPT_CODE_NOT_NULL", "Y");
            }
            break;
        case RptTemplateExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_EQUALS", "Y");
            } else {
                parms.put("AND_RPT_CODE_EQUALS", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptTemplateExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_RPT_CODE_NOT_EQUALS", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptTemplateExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_GT", "Y");
            } else {
                parms.put("AND_RPT_CODE_GT", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptTemplateExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_GE", "Y");
            } else {
                parms.put("AND_RPT_CODE_GE", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptTemplateExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_LT", "Y");
            } else {
                parms.put("AND_RPT_CODE_LT", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptTemplateExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_LE", "Y");
            } else {
                parms.put("AND_RPT_CODE_LE", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        case RptTemplateExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_RPT_CODE_LIKE", "Y");
            } else {
                parms.put("AND_RPT_CODE_LIKE", "Y");
            }
            parms.put("rptCode", example.getRptCode());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getPHYSICS_TABLEExampleParms(RptTemplateExample example) {
        Map parms = new HashMap();
        switch (example.getPhysicsTable_Indicator()) {
        case RptTemplateExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PHYSICS_TABLE_NULL", "Y");
            } else {
                parms.put("AND_PHYSICS_TABLE_NULL", "Y");
            }
            break;
        case RptTemplateExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PHYSICS_TABLE_NOT_NULL", "Y");
            } else {
                parms.put("AND_PHYSICS_TABLE_NOT_NULL", "Y");
            }
            break;
        case RptTemplateExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PHYSICS_TABLE_EQUALS", "Y");
            } else {
                parms.put("AND_PHYSICS_TABLE_EQUALS", "Y");
            }
            parms.put("physicsTable", example.getPhysicsTable());
            break;
        case RptTemplateExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PHYSICS_TABLE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_PHYSICS_TABLE_NOT_EQUALS", "Y");
            }
            parms.put("physicsTable", example.getPhysicsTable());
            break;
        case RptTemplateExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PHYSICS_TABLE_GT", "Y");
            } else {
                parms.put("AND_PHYSICS_TABLE_GT", "Y");
            }
            parms.put("physicsTable", example.getPhysicsTable());
            break;
        case RptTemplateExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PHYSICS_TABLE_GE", "Y");
            } else {
                parms.put("AND_PHYSICS_TABLE_GE", "Y");
            }
            parms.put("physicsTable", example.getPhysicsTable());
            break;
        case RptTemplateExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PHYSICS_TABLE_LT", "Y");
            } else {
                parms.put("AND_PHYSICS_TABLE_LT", "Y");
            }
            parms.put("physicsTable", example.getPhysicsTable());
            break;
        case RptTemplateExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PHYSICS_TABLE_LE", "Y");
            } else {
                parms.put("AND_PHYSICS_TABLE_LE", "Y");
            }
            parms.put("physicsTable", example.getPhysicsTable());
            break;
        case RptTemplateExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PHYSICS_TABLE_LIKE", "Y");
            } else {
                parms.put("AND_PHYSICS_TABLE_LIKE", "Y");
            }
            parms.put("physicsTable", example.getPhysicsTable());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getTEMPLATE_PATHExampleParms(RptTemplateExample example) {
        Map parms = new HashMap();
        switch (example.getTemplatePath_Indicator()) {
        case RptTemplateExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TEMPLATE_PATH_NULL", "Y");
            } else {
                parms.put("AND_TEMPLATE_PATH_NULL", "Y");
            }
            break;
        case RptTemplateExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TEMPLATE_PATH_NOT_NULL", "Y");
            } else {
                parms.put("AND_TEMPLATE_PATH_NOT_NULL", "Y");
            }
            break;
        case RptTemplateExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TEMPLATE_PATH_EQUALS", "Y");
            } else {
                parms.put("AND_TEMPLATE_PATH_EQUALS", "Y");
            }
            parms.put("templatePath", example.getTemplatePath());
            break;
        case RptTemplateExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TEMPLATE_PATH_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_TEMPLATE_PATH_NOT_EQUALS", "Y");
            }
            parms.put("templatePath", example.getTemplatePath());
            break;
        case RptTemplateExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TEMPLATE_PATH_GT", "Y");
            } else {
                parms.put("AND_TEMPLATE_PATH_GT", "Y");
            }
            parms.put("templatePath", example.getTemplatePath());
            break;
        case RptTemplateExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TEMPLATE_PATH_GE", "Y");
            } else {
                parms.put("AND_TEMPLATE_PATH_GE", "Y");
            }
            parms.put("templatePath", example.getTemplatePath());
            break;
        case RptTemplateExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TEMPLATE_PATH_LT", "Y");
            } else {
                parms.put("AND_TEMPLATE_PATH_LT", "Y");
            }
            parms.put("templatePath", example.getTemplatePath());
            break;
        case RptTemplateExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TEMPLATE_PATH_LE", "Y");
            } else {
                parms.put("AND_TEMPLATE_PATH_LE", "Y");
            }
            parms.put("templatePath", example.getTemplatePath());
            break;
        case RptTemplateExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_TEMPLATE_PATH_LIKE", "Y");
            } else {
                parms.put("AND_TEMPLATE_PATH_LIKE", "Y");
            }
            parms.put("templatePath", example.getTemplatePath());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getExampleParms(RptTemplateExample example) {
        Map parms = new HashMap();
        parms.putAll(getIDExampleParms(example));
        parms.putAll(getRPT_CODEExampleParms(example));
        parms.putAll(getPHYSICS_TABLEExampleParms(example));
        parms.putAll(getTEMPLATE_PATHExampleParms(example));
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int selectCountByExample(RptTemplateExample example) {
        Map parms = getExampleParms(example);
        int count = ((Integer)getSqlMapClientTemplate().queryForObject("rpt_template.abatorgenerated_selectCountByExample", parms)).intValue();
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(RptTemplateExample example, int pageSize, int pageNum, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        PageBox pageBox = new PageBox();
        PageObject pageObject = new PageObject();
        pageObject.setPageSize(pageSize);
        pageObject.setPageIndex(pageNum);
        int itemAmount = selectCountByExample(example);
        pageObject.setItemAmount(itemAmount);
        List pageList = null;
        if (pageObject.getBeginIndex() <= pageObject.getItemAmount()) {
            pageList = (getSqlMapClientTemplate().queryForList("rpt_template.abatorgenerated_selectByExample", parms, pageObject.getBeginIndex() - 1, pageSize));
        }
        pageBox.setPageObject(pageObject);
        pageBox.setPageList(pageList);
        return pageBox;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(RptTemplateExample example, int pageSize, int pageNum) {
        return selectByExampleWithPaging(example, pageSize, pageNum, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeyForCgs(RptTemplate record) {
        int rows = getSqlMapClientTemplate().update("rpt_template.abatorgenerated_updateByPrimaryKeyForCgs", record);
        return rows;
    }
}