package com.neteast.rmp.dao.impl;

import com.neteast.rmp.dao.ScCellParmsDAO;
import com.neteast.rmp.dao.domain.ScCellParms;
import com.neteast.rmp.dao.domain.ScCellParmsExample;
import com.neteast.rmp.dao.ibatis.ext.BaseSqlMapClientDaoSupport;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import com.seraph.bi.suite.support.domain.pagination.PageObject;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

@Repository
public class ScCellParmsDAOImpl extends BaseSqlMapClientDaoSupport implements ScCellParmsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public ScCellParmsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public Integer insert(ScCellParms record) {
        Object newKey = getSqlMapClientTemplate().insert("sc_cell_parms.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public int updateByPrimaryKey(ScCellParms record) {
        int rows = getSqlMapClientTemplate().update("sc_cell_parms.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public int updateByPrimaryKeySelective(ScCellParms record) {
        int rows = getSqlMapClientTemplate().update("sc_cell_parms.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public List selectByExample(ScCellParmsExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("sc_cell_parms.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public List selectByExample(ScCellParmsExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public ScCellParms selectByPrimaryKey(Integer id) {
        ScCellParms key = new ScCellParms();
        key.setId(id);
        ScCellParms record = (ScCellParms) getSqlMapClientTemplate().queryForObject("sc_cell_parms.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public int deleteByExample(ScCellParmsExample example) {
        int rows = getSqlMapClientTemplate().delete("sc_cell_parms.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) {
        ScCellParms key = new ScCellParms();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("sc_cell_parms.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getIDExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NULL", "Y");
            } else {
                parms.put("AND_ID_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_NULL", "Y");
            } else {
                parms.put("AND_ID_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_EQUALS", "Y");
            } else {
                parms.put("AND_ID_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ID_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GT", "Y");
            } else {
                parms.put("AND_ID_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GE", "Y");
            } else {
                parms.put("AND_ID_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LT", "Y");
            } else {
                parms.put("AND_ID_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LE", "Y");
            } else {
                parms.put("AND_ID_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getCELL_CODEExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getCellCode_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_CODE_NULL", "Y");
            } else {
                parms.put("AND_CELL_CODE_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_CODE_NOT_NULL", "Y");
            } else {
                parms.put("AND_CELL_CODE_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_CODE_EQUALS", "Y");
            } else {
                parms.put("AND_CELL_CODE_EQUALS", "Y");
            }
            parms.put("cellCode", example.getCellCode());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_CODE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_CELL_CODE_NOT_EQUALS", "Y");
            }
            parms.put("cellCode", example.getCellCode());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_CODE_GT", "Y");
            } else {
                parms.put("AND_CELL_CODE_GT", "Y");
            }
            parms.put("cellCode", example.getCellCode());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_CODE_GE", "Y");
            } else {
                parms.put("AND_CELL_CODE_GE", "Y");
            }
            parms.put("cellCode", example.getCellCode());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_CODE_LT", "Y");
            } else {
                parms.put("AND_CELL_CODE_LT", "Y");
            }
            parms.put("cellCode", example.getCellCode());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_CODE_LE", "Y");
            } else {
                parms.put("AND_CELL_CODE_LE", "Y");
            }
            parms.put("cellCode", example.getCellCode());
            break;
        case ScCellParmsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_CODE_LIKE", "Y");
            } else {
                parms.put("AND_CELL_CODE_LIKE", "Y");
            }
            parms.put("cellCode", example.getCellCode());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getPARM_CODEExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getParmCode_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_CODE_NULL", "Y");
            } else {
                parms.put("AND_PARM_CODE_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_CODE_NOT_NULL", "Y");
            } else {
                parms.put("AND_PARM_CODE_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_CODE_EQUALS", "Y");
            } else {
                parms.put("AND_PARM_CODE_EQUALS", "Y");
            }
            parms.put("parmCode", example.getParmCode());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_CODE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_PARM_CODE_NOT_EQUALS", "Y");
            }
            parms.put("parmCode", example.getParmCode());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_CODE_GT", "Y");
            } else {
                parms.put("AND_PARM_CODE_GT", "Y");
            }
            parms.put("parmCode", example.getParmCode());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_CODE_GE", "Y");
            } else {
                parms.put("AND_PARM_CODE_GE", "Y");
            }
            parms.put("parmCode", example.getParmCode());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_CODE_LT", "Y");
            } else {
                parms.put("AND_PARM_CODE_LT", "Y");
            }
            parms.put("parmCode", example.getParmCode());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_CODE_LE", "Y");
            } else {
                parms.put("AND_PARM_CODE_LE", "Y");
            }
            parms.put("parmCode", example.getParmCode());
            break;
        case ScCellParmsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_CODE_LIKE", "Y");
            } else {
                parms.put("AND_PARM_CODE_LIKE", "Y");
            }
            parms.put("parmCode", example.getParmCode());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getPARM_NAMEExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getParmName_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_NAME_NULL", "Y");
            } else {
                parms.put("AND_PARM_NAME_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_NAME_NOT_NULL", "Y");
            } else {
                parms.put("AND_PARM_NAME_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_NAME_EQUALS", "Y");
            } else {
                parms.put("AND_PARM_NAME_EQUALS", "Y");
            }
            parms.put("parmName", example.getParmName());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_NAME_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_PARM_NAME_NOT_EQUALS", "Y");
            }
            parms.put("parmName", example.getParmName());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_NAME_GT", "Y");
            } else {
                parms.put("AND_PARM_NAME_GT", "Y");
            }
            parms.put("parmName", example.getParmName());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_NAME_GE", "Y");
            } else {
                parms.put("AND_PARM_NAME_GE", "Y");
            }
            parms.put("parmName", example.getParmName());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_NAME_LT", "Y");
            } else {
                parms.put("AND_PARM_NAME_LT", "Y");
            }
            parms.put("parmName", example.getParmName());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_NAME_LE", "Y");
            } else {
                parms.put("AND_PARM_NAME_LE", "Y");
            }
            parms.put("parmName", example.getParmName());
            break;
        case ScCellParmsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_NAME_LIKE", "Y");
            } else {
                parms.put("AND_PARM_NAME_LIKE", "Y");
            }
            parms.put("parmName", example.getParmName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getPARM_TYPEExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getParmType_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_TYPE_NULL", "Y");
            } else {
                parms.put("AND_PARM_TYPE_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_TYPE_NOT_NULL", "Y");
            } else {
                parms.put("AND_PARM_TYPE_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_TYPE_EQUALS", "Y");
            } else {
                parms.put("AND_PARM_TYPE_EQUALS", "Y");
            }
            parms.put("parmType", example.getParmType());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_TYPE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_PARM_TYPE_NOT_EQUALS", "Y");
            }
            parms.put("parmType", example.getParmType());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_TYPE_GT", "Y");
            } else {
                parms.put("AND_PARM_TYPE_GT", "Y");
            }
            parms.put("parmType", example.getParmType());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_TYPE_GE", "Y");
            } else {
                parms.put("AND_PARM_TYPE_GE", "Y");
            }
            parms.put("parmType", example.getParmType());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_TYPE_LT", "Y");
            } else {
                parms.put("AND_PARM_TYPE_LT", "Y");
            }
            parms.put("parmType", example.getParmType());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_TYPE_LE", "Y");
            } else {
                parms.put("AND_PARM_TYPE_LE", "Y");
            }
            parms.put("parmType", example.getParmType());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getPARM_VALUEExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getParmValue_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_VALUE_NULL", "Y");
            } else {
                parms.put("AND_PARM_VALUE_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_VALUE_NOT_NULL", "Y");
            } else {
                parms.put("AND_PARM_VALUE_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_VALUE_EQUALS", "Y");
            } else {
                parms.put("AND_PARM_VALUE_EQUALS", "Y");
            }
            parms.put("parmValue", example.getParmValue());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_VALUE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_PARM_VALUE_NOT_EQUALS", "Y");
            }
            parms.put("parmValue", example.getParmValue());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_VALUE_GT", "Y");
            } else {
                parms.put("AND_PARM_VALUE_GT", "Y");
            }
            parms.put("parmValue", example.getParmValue());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_VALUE_GE", "Y");
            } else {
                parms.put("AND_PARM_VALUE_GE", "Y");
            }
            parms.put("parmValue", example.getParmValue());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_VALUE_LT", "Y");
            } else {
                parms.put("AND_PARM_VALUE_LT", "Y");
            }
            parms.put("parmValue", example.getParmValue());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_VALUE_LE", "Y");
            } else {
                parms.put("AND_PARM_VALUE_LE", "Y");
            }
            parms.put("parmValue", example.getParmValue());
            break;
        case ScCellParmsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_VALUE_LIKE", "Y");
            } else {
                parms.put("AND_PARM_VALUE_LIKE", "Y");
            }
            parms.put("parmValue", example.getParmValue());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getPARM_RANGEExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getParmRange_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_RANGE_NULL", "Y");
            } else {
                parms.put("AND_PARM_RANGE_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_RANGE_NOT_NULL", "Y");
            } else {
                parms.put("AND_PARM_RANGE_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_RANGE_EQUALS", "Y");
            } else {
                parms.put("AND_PARM_RANGE_EQUALS", "Y");
            }
            parms.put("parmRange", example.getParmRange());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_RANGE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_PARM_RANGE_NOT_EQUALS", "Y");
            }
            parms.put("parmRange", example.getParmRange());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_RANGE_GT", "Y");
            } else {
                parms.put("AND_PARM_RANGE_GT", "Y");
            }
            parms.put("parmRange", example.getParmRange());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_RANGE_GE", "Y");
            } else {
                parms.put("AND_PARM_RANGE_GE", "Y");
            }
            parms.put("parmRange", example.getParmRange());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_RANGE_LT", "Y");
            } else {
                parms.put("AND_PARM_RANGE_LT", "Y");
            }
            parms.put("parmRange", example.getParmRange());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_RANGE_LE", "Y");
            } else {
                parms.put("AND_PARM_RANGE_LE", "Y");
            }
            parms.put("parmRange", example.getParmRange());
            break;
        case ScCellParmsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARM_RANGE_LIKE", "Y");
            } else {
                parms.put("AND_PARM_RANGE_LIKE", "Y");
            }
            parms.put("parmRange", example.getParmRange());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getDIC_URLExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getDicUrl_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_URL_NULL", "Y");
            } else {
                parms.put("AND_DIC_URL_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_URL_NOT_NULL", "Y");
            } else {
                parms.put("AND_DIC_URL_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_URL_EQUALS", "Y");
            } else {
                parms.put("AND_DIC_URL_EQUALS", "Y");
            }
            parms.put("dicUrl", example.getDicUrl());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_URL_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_DIC_URL_NOT_EQUALS", "Y");
            }
            parms.put("dicUrl", example.getDicUrl());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_URL_GT", "Y");
            } else {
                parms.put("AND_DIC_URL_GT", "Y");
            }
            parms.put("dicUrl", example.getDicUrl());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_URL_GE", "Y");
            } else {
                parms.put("AND_DIC_URL_GE", "Y");
            }
            parms.put("dicUrl", example.getDicUrl());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_URL_LT", "Y");
            } else {
                parms.put("AND_DIC_URL_LT", "Y");
            }
            parms.put("dicUrl", example.getDicUrl());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_URL_LE", "Y");
            } else {
                parms.put("AND_DIC_URL_LE", "Y");
            }
            parms.put("dicUrl", example.getDicUrl());
            break;
        case ScCellParmsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_URL_LIKE", "Y");
            } else {
                parms.put("AND_DIC_URL_LIKE", "Y");
            }
            parms.put("dicUrl", example.getDicUrl());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getDIC_DISPLAY_FIELDExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getDicDisplayField_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_DISPLAY_FIELD_NULL", "Y");
            } else {
                parms.put("AND_DIC_DISPLAY_FIELD_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_DISPLAY_FIELD_NOT_NULL", "Y");
            } else {
                parms.put("AND_DIC_DISPLAY_FIELD_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_DISPLAY_FIELD_EQUALS", "Y");
            } else {
                parms.put("AND_DIC_DISPLAY_FIELD_EQUALS", "Y");
            }
            parms.put("dicDisplayField", example.getDicDisplayField());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_DISPLAY_FIELD_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_DIC_DISPLAY_FIELD_NOT_EQUALS", "Y");
            }
            parms.put("dicDisplayField", example.getDicDisplayField());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_DISPLAY_FIELD_GT", "Y");
            } else {
                parms.put("AND_DIC_DISPLAY_FIELD_GT", "Y");
            }
            parms.put("dicDisplayField", example.getDicDisplayField());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_DISPLAY_FIELD_GE", "Y");
            } else {
                parms.put("AND_DIC_DISPLAY_FIELD_GE", "Y");
            }
            parms.put("dicDisplayField", example.getDicDisplayField());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_DISPLAY_FIELD_LT", "Y");
            } else {
                parms.put("AND_DIC_DISPLAY_FIELD_LT", "Y");
            }
            parms.put("dicDisplayField", example.getDicDisplayField());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_DISPLAY_FIELD_LE", "Y");
            } else {
                parms.put("AND_DIC_DISPLAY_FIELD_LE", "Y");
            }
            parms.put("dicDisplayField", example.getDicDisplayField());
            break;
        case ScCellParmsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_DISPLAY_FIELD_LIKE", "Y");
            } else {
                parms.put("AND_DIC_DISPLAY_FIELD_LIKE", "Y");
            }
            parms.put("dicDisplayField", example.getDicDisplayField());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getDIC_VALUE_FIELDExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getDicValueField_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_VALUE_FIELD_NULL", "Y");
            } else {
                parms.put("AND_DIC_VALUE_FIELD_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_VALUE_FIELD_NOT_NULL", "Y");
            } else {
                parms.put("AND_DIC_VALUE_FIELD_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_VALUE_FIELD_EQUALS", "Y");
            } else {
                parms.put("AND_DIC_VALUE_FIELD_EQUALS", "Y");
            }
            parms.put("dicValueField", example.getDicValueField());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_VALUE_FIELD_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_DIC_VALUE_FIELD_NOT_EQUALS", "Y");
            }
            parms.put("dicValueField", example.getDicValueField());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_VALUE_FIELD_GT", "Y");
            } else {
                parms.put("AND_DIC_VALUE_FIELD_GT", "Y");
            }
            parms.put("dicValueField", example.getDicValueField());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_VALUE_FIELD_GE", "Y");
            } else {
                parms.put("AND_DIC_VALUE_FIELD_GE", "Y");
            }
            parms.put("dicValueField", example.getDicValueField());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_VALUE_FIELD_LT", "Y");
            } else {
                parms.put("AND_DIC_VALUE_FIELD_LT", "Y");
            }
            parms.put("dicValueField", example.getDicValueField());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_VALUE_FIELD_LE", "Y");
            } else {
                parms.put("AND_DIC_VALUE_FIELD_LE", "Y");
            }
            parms.put("dicValueField", example.getDicValueField());
            break;
        case ScCellParmsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DIC_VALUE_FIELD_LIKE", "Y");
            } else {
                parms.put("AND_DIC_VALUE_FIELD_LIKE", "Y");
            }
            parms.put("dicValueField", example.getDicValueField());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getSORTExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getSort_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_NULL", "Y");
            } else {
                parms.put("AND_SORT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_NOT_NULL", "Y");
            } else {
                parms.put("AND_SORT_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_EQUALS", "Y");
            } else {
                parms.put("AND_SORT_EQUALS", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_SORT_NOT_EQUALS", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_GT", "Y");
            } else {
                parms.put("AND_SORT_GT", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_GE", "Y");
            } else {
                parms.put("AND_SORT_GE", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_LT", "Y");
            } else {
                parms.put("AND_SORT_LT", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_LE", "Y");
            } else {
                parms.put("AND_SORT_LE", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getDESCRIPTIONExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        switch (example.getDescription_Indicator()) {
        case ScCellParmsExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_NULL", "Y");
            } else {
                parms.put("AND_DESCRIPTION_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_NOT_NULL", "Y");
            } else {
                parms.put("AND_DESCRIPTION_NOT_NULL", "Y");
            }
            break;
        case ScCellParmsExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_EQUALS", "Y");
            } else {
                parms.put("AND_DESCRIPTION_EQUALS", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellParmsExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_DESCRIPTION_NOT_EQUALS", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_GT", "Y");
            } else {
                parms.put("AND_DESCRIPTION_GT", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellParmsExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_GE", "Y");
            } else {
                parms.put("AND_DESCRIPTION_GE", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_LT", "Y");
            } else {
                parms.put("AND_DESCRIPTION_LT", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellParmsExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_LE", "Y");
            } else {
                parms.put("AND_DESCRIPTION_LE", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellParmsExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_LIKE", "Y");
            } else {
                parms.put("AND_DESCRIPTION_LIKE", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    private Map getExampleParms(ScCellParmsExample example) {
        Map parms = new HashMap();
        parms.putAll(getIDExampleParms(example));
        parms.putAll(getCELL_CODEExampleParms(example));
        parms.putAll(getPARM_CODEExampleParms(example));
        parms.putAll(getPARM_NAMEExampleParms(example));
        parms.putAll(getPARM_TYPEExampleParms(example));
        parms.putAll(getPARM_VALUEExampleParms(example));
        parms.putAll(getPARM_RANGEExampleParms(example));
        parms.putAll(getDIC_URLExampleParms(example));
        parms.putAll(getDIC_DISPLAY_FIELDExampleParms(example));
        parms.putAll(getDIC_VALUE_FIELDExampleParms(example));
        parms.putAll(getSORTExampleParms(example));
        parms.putAll(getDESCRIPTIONExampleParms(example));
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public int selectCountByExample(ScCellParmsExample example) {
        Map parms = getExampleParms(example);
        int count = ((Integer)getSqlMapClientTemplate().queryForObject("sc_cell_parms.abatorgenerated_selectCountByExample", parms)).intValue();
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public PageBox selectByExampleWithPaging(ScCellParmsExample example, int pageSize, int pageNum, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        PageBox pageBox = new PageBox();
        PageObject pageObject = new PageObject();
        pageObject.setPageSize(pageSize);
        pageObject.setPageIndex(pageNum);
        int itemAmount = selectCountByExample(example);
        pageObject.setItemAmount(itemAmount);
        List pageList = null;
        if (pageObject.getBeginIndex() <= pageObject.getItemAmount()) {
            pageList = (getSqlMapClientTemplate().queryForList("sc_cell_parms.abatorgenerated_selectByExample", parms, pageObject.getBeginIndex() - 1, pageSize));
        }
        pageBox.setPageObject(pageObject);
        pageBox.setPageList(pageList);
        return pageBox;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public PageBox selectByExampleWithPaging(ScCellParmsExample example, int pageSize, int pageNum) {
        return selectByExampleWithPaging(example, pageSize, pageNum, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    public int updateByPrimaryKeyForCgs(ScCellParms record) {
        int rows = getSqlMapClientTemplate().update("sc_cell_parms.abatorgenerated_updateByPrimaryKeyForCgs", record);
        return rows;
    }
}