package com.neteast.rmp.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neteast.rmp.dao.ScCellCfgDAO;
import com.neteast.rmp.dao.domain.ScCellCfg;
import com.neteast.rmp.dao.domain.ScCellCfgExample;
import com.neteast.rmp.dao.domain.ScCellCfgWithIdAndChildrenId;
import com.neteast.rmp.dao.ibatis.ext.BaseSqlMapClientDaoSupport;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import com.seraph.bi.suite.support.domain.pagination.PageObject;

@Repository
public class ScCellCfgDAOImpl extends BaseSqlMapClientDaoSupport implements ScCellCfgDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public ScCellCfgDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public Integer insert(ScCellCfg record) {
        Object newKey = getSqlMapClientTemplate().insert("sc_cell_cfg.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public int updateByPrimaryKey(ScCellCfg record) {
        int rows = getSqlMapClientTemplate().update("sc_cell_cfg.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public int updateByPrimaryKeySelective(ScCellCfg record) {
        int rows = getSqlMapClientTemplate().update("sc_cell_cfg.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public List selectByExample(ScCellCfgExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("sc_cell_cfg.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public List selectByExample(ScCellCfgExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public ScCellCfg selectByPrimaryKey(Integer id) {
        ScCellCfg key = new ScCellCfg();
        key.setId(id);
        ScCellCfg record = (ScCellCfg) getSqlMapClientTemplate().queryForObject("sc_cell_cfg.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public int deleteByExample(ScCellCfgExample example) {
        int rows = getSqlMapClientTemplate().delete("sc_cell_cfg.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) {
        ScCellCfg key = new ScCellCfg();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("sc_cell_cfg.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getIDExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NULL", "Y");
            } else {
                parms.put("AND_ID_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_NULL", "Y");
            } else {
                parms.put("AND_ID_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_EQUALS", "Y");
            } else {
                parms.put("AND_ID_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ID_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GT", "Y");
            } else {
                parms.put("AND_ID_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GE", "Y");
            } else {
                parms.put("AND_ID_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LT", "Y");
            } else {
                parms.put("AND_ID_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LE", "Y");
            } else {
                parms.put("AND_ID_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getPARENT_IDExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getParentId_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ID_NULL", "Y");
            } else {
                parms.put("AND_PARENT_ID_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ID_NOT_NULL", "Y");
            } else {
                parms.put("AND_PARENT_ID_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ID_EQUALS", "Y");
            } else {
                parms.put("AND_PARENT_ID_EQUALS", "Y");
            }
            parms.put("parentId", example.getParentId());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ID_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_PARENT_ID_NOT_EQUALS", "Y");
            }
            parms.put("parentId", example.getParentId());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ID_GT", "Y");
            } else {
                parms.put("AND_PARENT_ID_GT", "Y");
            }
            parms.put("parentId", example.getParentId());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ID_GE", "Y");
            } else {
                parms.put("AND_PARENT_ID_GE", "Y");
            }
            parms.put("parentId", example.getParentId());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ID_LT", "Y");
            } else {
                parms.put("AND_PARENT_ID_LT", "Y");
            }
            parms.put("parentId", example.getParentId());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ID_LE", "Y");
            } else {
                parms.put("AND_PARENT_ID_LE", "Y");
            }
            parms.put("parentId", example.getParentId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getPORTAL_CODEExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getPortalCode_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PORTAL_CODE_NULL", "Y");
            } else {
                parms.put("AND_PORTAL_CODE_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PORTAL_CODE_NOT_NULL", "Y");
            } else {
                parms.put("AND_PORTAL_CODE_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PORTAL_CODE_EQUALS", "Y");
            } else {
                parms.put("AND_PORTAL_CODE_EQUALS", "Y");
            }
            parms.put("portalCode", example.getPortalCode());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PORTAL_CODE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_PORTAL_CODE_NOT_EQUALS", "Y");
            }
            parms.put("portalCode", example.getPortalCode());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PORTAL_CODE_GT", "Y");
            } else {
                parms.put("AND_PORTAL_CODE_GT", "Y");
            }
            parms.put("portalCode", example.getPortalCode());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PORTAL_CODE_GE", "Y");
            } else {
                parms.put("AND_PORTAL_CODE_GE", "Y");
            }
            parms.put("portalCode", example.getPortalCode());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PORTAL_CODE_LT", "Y");
            } else {
                parms.put("AND_PORTAL_CODE_LT", "Y");
            }
            parms.put("portalCode", example.getPortalCode());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PORTAL_CODE_LE", "Y");
            } else {
                parms.put("AND_PORTAL_CODE_LE", "Y");
            }
            parms.put("portalCode", example.getPortalCode());
            break;
        case ScCellCfgExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PORTAL_CODE_LIKE", "Y");
            } else {
                parms.put("AND_PORTAL_CODE_LIKE", "Y");
            }
            parms.put("portalCode", example.getPortalCode());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getCELL_TITLEExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getCellTitle_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_TITLE_NULL", "Y");
            } else {
                parms.put("AND_CELL_TITLE_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_TITLE_NOT_NULL", "Y");
            } else {
                parms.put("AND_CELL_TITLE_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_TITLE_EQUALS", "Y");
            } else {
                parms.put("AND_CELL_TITLE_EQUALS", "Y");
            }
            parms.put("cellTitle", example.getCellTitle());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_TITLE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_CELL_TITLE_NOT_EQUALS", "Y");
            }
            parms.put("cellTitle", example.getCellTitle());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_TITLE_GT", "Y");
            } else {
                parms.put("AND_CELL_TITLE_GT", "Y");
            }
            parms.put("cellTitle", example.getCellTitle());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_TITLE_GE", "Y");
            } else {
                parms.put("AND_CELL_TITLE_GE", "Y");
            }
            parms.put("cellTitle", example.getCellTitle());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_TITLE_LT", "Y");
            } else {
                parms.put("AND_CELL_TITLE_LT", "Y");
            }
            parms.put("cellTitle", example.getCellTitle());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_TITLE_LE", "Y");
            } else {
                parms.put("AND_CELL_TITLE_LE", "Y");
            }
            parms.put("cellTitle", example.getCellTitle());
            break;
        case ScCellCfgExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CELL_TITLE_LIKE", "Y");
            } else {
                parms.put("AND_CELL_TITLE_LIKE", "Y");
            }
            parms.put("cellTitle", example.getCellTitle());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getHREFExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getHref_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HREF_NULL", "Y");
            } else {
                parms.put("AND_HREF_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HREF_NOT_NULL", "Y");
            } else {
                parms.put("AND_HREF_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HREF_EQUALS", "Y");
            } else {
                parms.put("AND_HREF_EQUALS", "Y");
            }
            parms.put("href", example.getHref());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HREF_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_HREF_NOT_EQUALS", "Y");
            }
            parms.put("href", example.getHref());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HREF_GT", "Y");
            } else {
                parms.put("AND_HREF_GT", "Y");
            }
            parms.put("href", example.getHref());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HREF_GE", "Y");
            } else {
                parms.put("AND_HREF_GE", "Y");
            }
            parms.put("href", example.getHref());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HREF_LT", "Y");
            } else {
                parms.put("AND_HREF_LT", "Y");
            }
            parms.put("href", example.getHref());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HREF_LE", "Y");
            } else {
                parms.put("AND_HREF_LE", "Y");
            }
            parms.put("href", example.getHref());
            break;
        case ScCellCfgExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HREF_LIKE", "Y");
            } else {
                parms.put("AND_HREF_LIKE", "Y");
            }
            parms.put("href", example.getHref());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getROW_NUMExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getRowNum_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROW_NUM_NULL", "Y");
            } else {
                parms.put("AND_ROW_NUM_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROW_NUM_NOT_NULL", "Y");
            } else {
                parms.put("AND_ROW_NUM_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROW_NUM_EQUALS", "Y");
            } else {
                parms.put("AND_ROW_NUM_EQUALS", "Y");
            }
            parms.put("rowNum", example.getRowNum());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROW_NUM_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ROW_NUM_NOT_EQUALS", "Y");
            }
            parms.put("rowNum", example.getRowNum());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROW_NUM_GT", "Y");
            } else {
                parms.put("AND_ROW_NUM_GT", "Y");
            }
            parms.put("rowNum", example.getRowNum());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROW_NUM_GE", "Y");
            } else {
                parms.put("AND_ROW_NUM_GE", "Y");
            }
            parms.put("rowNum", example.getRowNum());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROW_NUM_LT", "Y");
            } else {
                parms.put("AND_ROW_NUM_LT", "Y");
            }
            parms.put("rowNum", example.getRowNum());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROW_NUM_LE", "Y");
            } else {
                parms.put("AND_ROW_NUM_LE", "Y");
            }
            parms.put("rowNum", example.getRowNum());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getCOL_NUMExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getColNum_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NUM_NULL", "Y");
            } else {
                parms.put("AND_COL_NUM_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NUM_NOT_NULL", "Y");
            } else {
                parms.put("AND_COL_NUM_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NUM_EQUALS", "Y");
            } else {
                parms.put("AND_COL_NUM_EQUALS", "Y");
            }
            parms.put("colNum", example.getColNum());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NUM_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_COL_NUM_NOT_EQUALS", "Y");
            }
            parms.put("colNum", example.getColNum());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NUM_GT", "Y");
            } else {
                parms.put("AND_COL_NUM_GT", "Y");
            }
            parms.put("colNum", example.getColNum());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NUM_GE", "Y");
            } else {
                parms.put("AND_COL_NUM_GE", "Y");
            }
            parms.put("colNum", example.getColNum());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NUM_LT", "Y");
            } else {
                parms.put("AND_COL_NUM_LT", "Y");
            }
            parms.put("colNum", example.getColNum());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_COL_NUM_LE", "Y");
            } else {
                parms.put("AND_COL_NUM_LE", "Y");
            }
            parms.put("colNum", example.getColNum());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getWIDTHExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getWidth_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_WIDTH_NULL", "Y");
            } else {
                parms.put("AND_WIDTH_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_WIDTH_NOT_NULL", "Y");
            } else {
                parms.put("AND_WIDTH_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_WIDTH_EQUALS", "Y");
            } else {
                parms.put("AND_WIDTH_EQUALS", "Y");
            }
            parms.put("width", example.getWidth());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_WIDTH_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_WIDTH_NOT_EQUALS", "Y");
            }
            parms.put("width", example.getWidth());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_WIDTH_GT", "Y");
            } else {
                parms.put("AND_WIDTH_GT", "Y");
            }
            parms.put("width", example.getWidth());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_WIDTH_GE", "Y");
            } else {
                parms.put("AND_WIDTH_GE", "Y");
            }
            parms.put("width", example.getWidth());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_WIDTH_LT", "Y");
            } else {
                parms.put("AND_WIDTH_LT", "Y");
            }
            parms.put("width", example.getWidth());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_WIDTH_LE", "Y");
            } else {
                parms.put("AND_WIDTH_LE", "Y");
            }
            parms.put("width", example.getWidth());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getHEIGHTExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getHeight_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HEIGHT_NULL", "Y");
            } else {
                parms.put("AND_HEIGHT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HEIGHT_NOT_NULL", "Y");
            } else {
                parms.put("AND_HEIGHT_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HEIGHT_EQUALS", "Y");
            } else {
                parms.put("AND_HEIGHT_EQUALS", "Y");
            }
            parms.put("height", example.getHeight());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HEIGHT_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_HEIGHT_NOT_EQUALS", "Y");
            }
            parms.put("height", example.getHeight());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HEIGHT_GT", "Y");
            } else {
                parms.put("AND_HEIGHT_GT", "Y");
            }
            parms.put("height", example.getHeight());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HEIGHT_GE", "Y");
            } else {
                parms.put("AND_HEIGHT_GE", "Y");
            }
            parms.put("height", example.getHeight());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HEIGHT_LT", "Y");
            } else {
                parms.put("AND_HEIGHT_LT", "Y");
            }
            parms.put("height", example.getHeight());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_HEIGHT_LE", "Y");
            } else {
                parms.put("AND_HEIGHT_LE", "Y");
            }
            parms.put("height", example.getHeight());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getNOTICE_MEExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getNoticeMe_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_NOTICE_ME_NULL", "Y");
            } else {
                parms.put("AND_NOTICE_ME_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_NOTICE_ME_NOT_NULL", "Y");
            } else {
                parms.put("AND_NOTICE_ME_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_NOTICE_ME_EQUALS", "Y");
            } else {
                parms.put("AND_NOTICE_ME_EQUALS", "Y");
            }
            parms.put("noticeMe", example.getNoticeMe());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_NOTICE_ME_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_NOTICE_ME_NOT_EQUALS", "Y");
            }
            parms.put("noticeMe", example.getNoticeMe());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_NOTICE_ME_GT", "Y");
            } else {
                parms.put("AND_NOTICE_ME_GT", "Y");
            }
            parms.put("noticeMe", example.getNoticeMe());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_NOTICE_ME_GE", "Y");
            } else {
                parms.put("AND_NOTICE_ME_GE", "Y");
            }
            parms.put("noticeMe", example.getNoticeMe());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_NOTICE_ME_LT", "Y");
            } else {
                parms.put("AND_NOTICE_ME_LT", "Y");
            }
            parms.put("noticeMe", example.getNoticeMe());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_NOTICE_ME_LE", "Y");
            } else {
                parms.put("AND_NOTICE_ME_LE", "Y");
            }
            parms.put("noticeMe", example.getNoticeMe());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getSORTExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getSort_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_NULL", "Y");
            } else {
                parms.put("AND_SORT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_NOT_NULL", "Y");
            } else {
                parms.put("AND_SORT_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_EQUALS", "Y");
            } else {
                parms.put("AND_SORT_EQUALS", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_SORT_NOT_EQUALS", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_GT", "Y");
            } else {
                parms.put("AND_SORT_GT", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_GE", "Y");
            } else {
                parms.put("AND_SORT_GE", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_LT", "Y");
            } else {
                parms.put("AND_SORT_LT", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_SORT_LE", "Y");
            } else {
                parms.put("AND_SORT_LE", "Y");
            }
            parms.put("sort", example.getSort());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getDESCRIPTIONExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        switch (example.getDescription_Indicator()) {
        case ScCellCfgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_NULL", "Y");
            } else {
                parms.put("AND_DESCRIPTION_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_NOT_NULL", "Y");
            } else {
                parms.put("AND_DESCRIPTION_NOT_NULL", "Y");
            }
            break;
        case ScCellCfgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_EQUALS", "Y");
            } else {
                parms.put("AND_DESCRIPTION_EQUALS", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellCfgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_DESCRIPTION_NOT_EQUALS", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_GT", "Y");
            } else {
                parms.put("AND_DESCRIPTION_GT", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellCfgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_GE", "Y");
            } else {
                parms.put("AND_DESCRIPTION_GE", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_LT", "Y");
            } else {
                parms.put("AND_DESCRIPTION_LT", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellCfgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_LE", "Y");
            } else {
                parms.put("AND_DESCRIPTION_LE", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        case ScCellCfgExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_DESCRIPTION_LIKE", "Y");
            } else {
                parms.put("AND_DESCRIPTION_LIKE", "Y");
            }
            parms.put("description", example.getDescription());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    private Map getExampleParms(ScCellCfgExample example) {
        Map parms = new HashMap();
        parms.putAll(getIDExampleParms(example));
        parms.putAll(getPARENT_IDExampleParms(example));
        parms.putAll(getPORTAL_CODEExampleParms(example));
        parms.putAll(getCELL_TITLEExampleParms(example));
        parms.putAll(getHREFExampleParms(example));
        parms.putAll(getROW_NUMExampleParms(example));
        parms.putAll(getCOL_NUMExampleParms(example));
        parms.putAll(getWIDTHExampleParms(example));
        parms.putAll(getHEIGHTExampleParms(example));
        parms.putAll(getNOTICE_MEExampleParms(example));
        parms.putAll(getSORTExampleParms(example));
        parms.putAll(getDESCRIPTIONExampleParms(example));
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public int selectCountByExample(ScCellCfgExample example) {
        Map parms = getExampleParms(example);
        int count = ((Integer)getSqlMapClientTemplate().queryForObject("sc_cell_cfg.abatorgenerated_selectCountByExample", parms)).intValue();
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public PageBox selectByExampleWithPaging(ScCellCfgExample example, int pageSize, int pageNum, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        PageBox pageBox = new PageBox();
        PageObject pageObject = new PageObject();
        pageObject.setPageSize(pageSize);
        pageObject.setPageIndex(pageNum);
        int itemAmount = selectCountByExample(example);
        pageObject.setItemAmount(itemAmount);
        List pageList = null;
        if (pageObject.getBeginIndex() <= pageObject.getItemAmount()) {
            pageList = (getSqlMapClientTemplate().queryForList("sc_cell_cfg.abatorgenerated_selectByExample", parms, pageObject.getBeginIndex() - 1, pageSize));
        }
        pageBox.setPageObject(pageObject);
        pageBox.setPageList(pageList);
        return pageBox;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public PageBox selectByExampleWithPaging(ScCellCfgExample example, int pageSize, int pageNum) {
        return selectByExampleWithPaging(example, pageSize, pageNum, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Wed Apr 10 21:26:34 CST 2013
     */
    public int updateByPrimaryKeyForCgs(ScCellCfg record) {
        int rows = getSqlMapClientTemplate().update("sc_cell_cfg.abatorgenerated_updateByPrimaryKeyForCgs", record);
        return rows;
    }

    public int editDescription(Map map) {
        int rows = getSqlMapClientTemplate().update("sc_cell_cfg.editDescription", map);
        return rows;
    }
	@Override
	public List<ScCellCfgWithIdAndChildrenId> selectIdAndChildrenId(String portalCode) {
		 List list = getSqlMapClientTemplate().queryForList("sc_cell_cfg.selectIdAndChildrenId", portalCode);
	     return list;
	}
}
