package com.neteast.rmp.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neteast.rmp.dao.ScOrgRelationDAO;
import com.neteast.rmp.dao.domain.ScOrgRelation;
import com.neteast.rmp.dao.domain.ScOrgRelationExample;
import com.neteast.rmp.dao.ibatis.ext.BaseSqlMapClientDaoSupport;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import com.seraph.bi.suite.support.domain.pagination.PageObject;

@Repository
public class ScOrgRelationDAOImpl extends BaseSqlMapClientDaoSupport implements ScOrgRelationDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public ScOrgRelationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer insert(ScOrgRelation record) {
        Object newKey = getSqlMapClientTemplate().insert("sc_org_relation.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKey(ScOrgRelation record) {
        int rows = getSqlMapClientTemplate().update("sc_org_relation.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeySelective(ScOrgRelation record) {
        int rows = getSqlMapClientTemplate().update("sc_org_relation.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(ScOrgRelationExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("sc_org_relation.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(ScOrgRelationExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public ScOrgRelation selectByPrimaryKey(Integer id) {
        ScOrgRelation key = new ScOrgRelation();
        key.setId(id);
        ScOrgRelation record = (ScOrgRelation) getSqlMapClientTemplate().queryForObject("sc_org_relation.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByExample(ScOrgRelationExample example) {
        int rows = getSqlMapClientTemplate().delete("sc_org_relation.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        ScOrgRelation key = new ScOrgRelation();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("sc_org_relation.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getIDExampleParms(ScOrgRelationExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case ScOrgRelationExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NULL", "Y");
            } else {
                parms.put("AND_ID_NULL", "Y");
            }
            break;
        case ScOrgRelationExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_NULL", "Y");
            } else {
                parms.put("AND_ID_NOT_NULL", "Y");
            }
            break;
        case ScOrgRelationExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_EQUALS", "Y");
            } else {
                parms.put("AND_ID_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScOrgRelationExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ID_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScOrgRelationExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GT", "Y");
            } else {
                parms.put("AND_ID_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScOrgRelationExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GE", "Y");
            } else {
                parms.put("AND_ID_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScOrgRelationExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LT", "Y");
            } else {
                parms.put("AND_ID_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScOrgRelationExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LE", "Y");
            } else {
                parms.put("AND_ID_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getCURR_ORG_CODEExampleParms(ScOrgRelationExample example) {
        Map parms = new HashMap();
        switch (example.getCurrOrgCode_Indicator()) {
        case ScOrgRelationExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CURR_ORG_CODE_NULL", "Y");
            } else {
                parms.put("AND_CURR_ORG_CODE_NULL", "Y");
            }
            break;
        case ScOrgRelationExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CURR_ORG_CODE_NOT_NULL", "Y");
            } else {
                parms.put("AND_CURR_ORG_CODE_NOT_NULL", "Y");
            }
            break;
        case ScOrgRelationExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CURR_ORG_CODE_EQUALS", "Y");
            } else {
                parms.put("AND_CURR_ORG_CODE_EQUALS", "Y");
            }
            parms.put("currOrgCode", example.getCurrOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CURR_ORG_CODE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_CURR_ORG_CODE_NOT_EQUALS", "Y");
            }
            parms.put("currOrgCode", example.getCurrOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CURR_ORG_CODE_GT", "Y");
            } else {
                parms.put("AND_CURR_ORG_CODE_GT", "Y");
            }
            parms.put("currOrgCode", example.getCurrOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CURR_ORG_CODE_GE", "Y");
            } else {
                parms.put("AND_CURR_ORG_CODE_GE", "Y");
            }
            parms.put("currOrgCode", example.getCurrOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CURR_ORG_CODE_LT", "Y");
            } else {
                parms.put("AND_CURR_ORG_CODE_LT", "Y");
            }
            parms.put("currOrgCode", example.getCurrOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CURR_ORG_CODE_LE", "Y");
            } else {
                parms.put("AND_CURR_ORG_CODE_LE", "Y");
            }
            parms.put("currOrgCode", example.getCurrOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_CURR_ORG_CODE_LIKE", "Y");
            } else {
                parms.put("AND_CURR_ORG_CODE_LIKE", "Y");
            }
            parms.put("currOrgCode", example.getCurrOrgCode());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getPARENT_ORG_CODEExampleParms(ScOrgRelationExample example) {
        Map parms = new HashMap();
        switch (example.getParentOrgCode_Indicator()) {
        case ScOrgRelationExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ORG_CODE_NULL", "Y");
            } else {
                parms.put("AND_PARENT_ORG_CODE_NULL", "Y");
            }
            break;
        case ScOrgRelationExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ORG_CODE_NOT_NULL", "Y");
            } else {
                parms.put("AND_PARENT_ORG_CODE_NOT_NULL", "Y");
            }
            break;
        case ScOrgRelationExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ORG_CODE_EQUALS", "Y");
            } else {
                parms.put("AND_PARENT_ORG_CODE_EQUALS", "Y");
            }
            parms.put("parentOrgCode", example.getParentOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ORG_CODE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_PARENT_ORG_CODE_NOT_EQUALS", "Y");
            }
            parms.put("parentOrgCode", example.getParentOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ORG_CODE_GT", "Y");
            } else {
                parms.put("AND_PARENT_ORG_CODE_GT", "Y");
            }
            parms.put("parentOrgCode", example.getParentOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ORG_CODE_GE", "Y");
            } else {
                parms.put("AND_PARENT_ORG_CODE_GE", "Y");
            }
            parms.put("parentOrgCode", example.getParentOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ORG_CODE_LT", "Y");
            } else {
                parms.put("AND_PARENT_ORG_CODE_LT", "Y");
            }
            parms.put("parentOrgCode", example.getParentOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ORG_CODE_LE", "Y");
            } else {
                parms.put("AND_PARENT_ORG_CODE_LE", "Y");
            }
            parms.put("parentOrgCode", example.getParentOrgCode());
            break;
        case ScOrgRelationExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_PARENT_ORG_CODE_LIKE", "Y");
            } else {
                parms.put("AND_PARENT_ORG_CODE_LIKE", "Y");
            }
            parms.put("parentOrgCode", example.getParentOrgCode());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getLEAF_SIGNExampleParms(ScOrgRelationExample example) {
        Map parms = new HashMap();
        switch (example.getLeafSign_Indicator()) {
        case ScOrgRelationExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_LEAF_SIGN_NULL", "Y");
            } else {
                parms.put("AND_LEAF_SIGN_NULL", "Y");
            }
            break;
        case ScOrgRelationExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_LEAF_SIGN_NOT_NULL", "Y");
            } else {
                parms.put("AND_LEAF_SIGN_NOT_NULL", "Y");
            }
            break;
        case ScOrgRelationExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_LEAF_SIGN_EQUALS", "Y");
            } else {
                parms.put("AND_LEAF_SIGN_EQUALS", "Y");
            }
            parms.put("leafSign", example.getLeafSign());
            break;
        case ScOrgRelationExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_LEAF_SIGN_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_LEAF_SIGN_NOT_EQUALS", "Y");
            }
            parms.put("leafSign", example.getLeafSign());
            break;
        case ScOrgRelationExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_LEAF_SIGN_GT", "Y");
            } else {
                parms.put("AND_LEAF_SIGN_GT", "Y");
            }
            parms.put("leafSign", example.getLeafSign());
            break;
        case ScOrgRelationExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_LEAF_SIGN_GE", "Y");
            } else {
                parms.put("AND_LEAF_SIGN_GE", "Y");
            }
            parms.put("leafSign", example.getLeafSign());
            break;
        case ScOrgRelationExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_LEAF_SIGN_LT", "Y");
            } else {
                parms.put("AND_LEAF_SIGN_LT", "Y");
            }
            parms.put("leafSign", example.getLeafSign());
            break;
        case ScOrgRelationExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_LEAF_SIGN_LE", "Y");
            } else {
                parms.put("AND_LEAF_SIGN_LE", "Y");
            }
            parms.put("leafSign", example.getLeafSign());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getExampleParms(ScOrgRelationExample example) {
        Map parms = new HashMap();
        parms.putAll(getIDExampleParms(example));
        parms.putAll(getCURR_ORG_CODEExampleParms(example));
        parms.putAll(getPARENT_ORG_CODEExampleParms(example));
        parms.putAll(getLEAF_SIGNExampleParms(example));
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int selectCountByExample(ScOrgRelationExample example) {
        Map parms = getExampleParms(example);
        int count = ((Integer)getSqlMapClientTemplate().queryForObject("sc_org_relation.abatorgenerated_selectCountByExample", parms)).intValue();
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(ScOrgRelationExample example, int pageSize, int pageNum, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        PageBox pageBox = new PageBox();
        PageObject pageObject = new PageObject();
        pageObject.setPageSize(pageSize);
        pageObject.setPageIndex(pageNum);
        int itemAmount = selectCountByExample(example);
        pageObject.setItemAmount(itemAmount);
        List pageList = null;
        if (pageObject.getBeginIndex() <= pageObject.getItemAmount()) {
            pageList = (getSqlMapClientTemplate().queryForList("sc_org_relation.abatorgenerated_selectByExample", parms, pageObject.getBeginIndex() - 1, pageSize));
        }
        pageBox.setPageObject(pageObject);
        pageBox.setPageList(pageList);
        return pageBox;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(ScOrgRelationExample example, int pageSize, int pageNum) {
        return selectByExampleWithPaging(example, pageSize, pageNum, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_relation
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeyForCgs(ScOrgRelation record) {
        int rows = getSqlMapClientTemplate().update("sc_org_relation.abatorgenerated_updateByPrimaryKeyForCgs", record);
        return rows;
    }
}