package com.neteast.rmp.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neteast.rmp.dao.ScOrgDAO;
import com.neteast.rmp.dao.domain.ScOrg;
import com.neteast.rmp.dao.domain.ScOrgExample;
import com.neteast.rmp.dao.ibatis.ext.BaseSqlMapClientDaoSupport;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import com.seraph.bi.suite.support.domain.pagination.PageObject;

@Repository
public class ScOrgDAOImpl extends BaseSqlMapClientDaoSupport implements ScOrgDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public ScOrgDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer insert(ScOrg record) {
        Object newKey = getSqlMapClientTemplate().insert("sc_org.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKey(ScOrg record) {
        int rows = getSqlMapClientTemplate().update("sc_org.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeySelective(ScOrg record) {
        int rows = getSqlMapClientTemplate().update("sc_org.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByCurrUserOrg(String orgCode) {
    	Map parms = new HashMap();
    	parms.put("orgCode", orgCode);
        List list = getSqlMapClientTemplate().queryForList("sc_org.abatorgenerated_selectByCurrUserOrg", parms);
        return list;
    }
    
    public List selectByExample(ScOrgExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("sc_org.abatorgenerated_selectByExample", parms);
        return list;
    }    

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(ScOrgExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public ScOrg selectByPrimaryKey(Integer id) {
        ScOrg key = new ScOrg();
        key.setId(id);
        ScOrg record = (ScOrg) getSqlMapClientTemplate().queryForObject("sc_org.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByExample(ScOrgExample example) {
        int rows = getSqlMapClientTemplate().delete("sc_org.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        ScOrg key = new ScOrg();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("sc_org.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getIDExampleParms(ScOrgExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case ScOrgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NULL", "Y");
            } else {
                parms.put("AND_ID_NULL", "Y");
            }
            break;
        case ScOrgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_NULL", "Y");
            } else {
                parms.put("AND_ID_NOT_NULL", "Y");
            }
            break;
        case ScOrgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_EQUALS", "Y");
            } else {
                parms.put("AND_ID_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScOrgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ID_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScOrgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GT", "Y");
            } else {
                parms.put("AND_ID_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScOrgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GE", "Y");
            } else {
                parms.put("AND_ID_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScOrgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LT", "Y");
            } else {
                parms.put("AND_ID_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScOrgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LE", "Y");
            } else {
                parms.put("AND_ID_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getORG_CODEExampleParms(ScOrgExample example) {
        Map parms = new HashMap();
        switch (example.getOrgCode_Indicator()) {
        case ScOrgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_CODE_NULL", "Y");
            } else {
                parms.put("AND_ORG_CODE_NULL", "Y");
            }
            break;
        case ScOrgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_CODE_NOT_NULL", "Y");
            } else {
                parms.put("AND_ORG_CODE_NOT_NULL", "Y");
            }
            break;
        case ScOrgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_CODE_EQUALS", "Y");
            } else {
                parms.put("AND_ORG_CODE_EQUALS", "Y");
            }
            parms.put("orgCode", example.getOrgCode());
            break;
        case ScOrgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_CODE_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ORG_CODE_NOT_EQUALS", "Y");
            }
            parms.put("orgCode", example.getOrgCode());
            break;
        case ScOrgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_CODE_GT", "Y");
            } else {
                parms.put("AND_ORG_CODE_GT", "Y");
            }
            parms.put("orgCode", example.getOrgCode());
            break;
        case ScOrgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_CODE_GE", "Y");
            } else {
                parms.put("AND_ORG_CODE_GE", "Y");
            }
            parms.put("orgCode", example.getOrgCode());
            break;
        case ScOrgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_CODE_LT", "Y");
            } else {
                parms.put("AND_ORG_CODE_LT", "Y");
            }
            parms.put("orgCode", example.getOrgCode());
            break;
        case ScOrgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_CODE_LE", "Y");
            } else {
                parms.put("AND_ORG_CODE_LE", "Y");
            }
            parms.put("orgCode", example.getOrgCode());
            break;
        case ScOrgExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_CODE_LIKE", "Y");
            } else {
                parms.put("AND_ORG_CODE_LIKE", "Y");
            }
            parms.put("orgCode", example.getOrgCode());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getORG_NAMEExampleParms(ScOrgExample example) {
        Map parms = new HashMap();
        switch (example.getOrgName_Indicator()) {
        case ScOrgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_NAME_NULL", "Y");
            } else {
                parms.put("AND_ORG_NAME_NULL", "Y");
            }
            break;
        case ScOrgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_NAME_NOT_NULL", "Y");
            } else {
                parms.put("AND_ORG_NAME_NOT_NULL", "Y");
            }
            break;
        case ScOrgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_NAME_EQUALS", "Y");
            } else {
                parms.put("AND_ORG_NAME_EQUALS", "Y");
            }
            parms.put("orgName", example.getOrgName());
            break;
        case ScOrgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_NAME_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ORG_NAME_NOT_EQUALS", "Y");
            }
            parms.put("orgName", example.getOrgName());
            break;
        case ScOrgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_NAME_GT", "Y");
            } else {
                parms.put("AND_ORG_NAME_GT", "Y");
            }
            parms.put("orgName", example.getOrgName());
            break;
        case ScOrgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_NAME_GE", "Y");
            } else {
                parms.put("AND_ORG_NAME_GE", "Y");
            }
            parms.put("orgName", example.getOrgName());
            break;
        case ScOrgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_NAME_LT", "Y");
            } else {
                parms.put("AND_ORG_NAME_LT", "Y");
            }
            parms.put("orgName", example.getOrgName());
            break;
        case ScOrgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_NAME_LE", "Y");
            } else {
                parms.put("AND_ORG_NAME_LE", "Y");
            }
            parms.put("orgName", example.getOrgName());
            break;
        case ScOrgExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_NAME_LIKE", "Y");
            } else {
                parms.put("AND_ORG_NAME_LIKE", "Y");
            }
            parms.put("orgName", example.getOrgName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getORG_SHORT_NAMEExampleParms(ScOrgExample example) {
        Map parms = new HashMap();
        switch (example.getOrgShortName_Indicator()) {
        case ScOrgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_SHORT_NAME_NULL", "Y");
            } else {
                parms.put("AND_ORG_SHORT_NAME_NULL", "Y");
            }
            break;
        case ScOrgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_SHORT_NAME_NOT_NULL", "Y");
            } else {
                parms.put("AND_ORG_SHORT_NAME_NOT_NULL", "Y");
            }
            break;
        case ScOrgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_SHORT_NAME_EQUALS", "Y");
            } else {
                parms.put("AND_ORG_SHORT_NAME_EQUALS", "Y");
            }
            parms.put("orgShortName", example.getOrgShortName());
            break;
        case ScOrgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_SHORT_NAME_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ORG_SHORT_NAME_NOT_EQUALS", "Y");
            }
            parms.put("orgShortName", example.getOrgShortName());
            break;
        case ScOrgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_SHORT_NAME_GT", "Y");
            } else {
                parms.put("AND_ORG_SHORT_NAME_GT", "Y");
            }
            parms.put("orgShortName", example.getOrgShortName());
            break;
        case ScOrgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_SHORT_NAME_GE", "Y");
            } else {
                parms.put("AND_ORG_SHORT_NAME_GE", "Y");
            }
            parms.put("orgShortName", example.getOrgShortName());
            break;
        case ScOrgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_SHORT_NAME_LT", "Y");
            } else {
                parms.put("AND_ORG_SHORT_NAME_LT", "Y");
            }
            parms.put("orgShortName", example.getOrgShortName());
            break;
        case ScOrgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_SHORT_NAME_LE", "Y");
            } else {
                parms.put("AND_ORG_SHORT_NAME_LE", "Y");
            }
            parms.put("orgShortName", example.getOrgShortName());
            break;
        case ScOrgExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_SHORT_NAME_LIKE", "Y");
            } else {
                parms.put("AND_ORG_SHORT_NAME_LIKE", "Y");
            }
            parms.put("orgShortName", example.getOrgShortName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getORG_LEVELExampleParms(ScOrgExample example) {
        Map parms = new HashMap();
        switch (example.getOrgLevel_Indicator()) {
        case ScOrgExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_LEVEL_NULL", "Y");
            } else {
                parms.put("AND_ORG_LEVEL_NULL", "Y");
            }
            break;
        case ScOrgExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_LEVEL_NOT_NULL", "Y");
            } else {
                parms.put("AND_ORG_LEVEL_NOT_NULL", "Y");
            }
            break;
        case ScOrgExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_LEVEL_EQUALS", "Y");
            } else {
                parms.put("AND_ORG_LEVEL_EQUALS", "Y");
            }
            parms.put("orgLevel", example.getOrgLevel());
            break;
        case ScOrgExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_LEVEL_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ORG_LEVEL_NOT_EQUALS", "Y");
            }
            parms.put("orgLevel", example.getOrgLevel());
            break;
        case ScOrgExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_LEVEL_GT", "Y");
            } else {
                parms.put("AND_ORG_LEVEL_GT", "Y");
            }
            parms.put("orgLevel", example.getOrgLevel());
            break;
        case ScOrgExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_LEVEL_GE", "Y");
            } else {
                parms.put("AND_ORG_LEVEL_GE", "Y");
            }
            parms.put("orgLevel", example.getOrgLevel());
            break;
        case ScOrgExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_LEVEL_LT", "Y");
            } else {
                parms.put("AND_ORG_LEVEL_LT", "Y");
            }
            parms.put("orgLevel", example.getOrgLevel());
            break;
        case ScOrgExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ORG_LEVEL_LE", "Y");
            } else {
                parms.put("AND_ORG_LEVEL_LE", "Y");
            }
            parms.put("orgLevel", example.getOrgLevel());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getExampleParms(ScOrgExample example) {
        Map parms = new HashMap();
        parms.putAll(getIDExampleParms(example));
        parms.putAll(getORG_CODEExampleParms(example));
        parms.putAll(getORG_NAMEExampleParms(example));
        parms.putAll(getORG_SHORT_NAMEExampleParms(example));
        parms.putAll(getORG_LEVELExampleParms(example));
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int selectCountByExample(ScOrgExample example) {
        Map parms = getExampleParms(example);
        int count = ((Integer)getSqlMapClientTemplate().queryForObject("sc_org.abatorgenerated_selectCountByExample", parms)).intValue();
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(ScOrgExample example, int pageSize, int pageNum, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        PageBox pageBox = new PageBox();
        PageObject pageObject = new PageObject();
        pageObject.setPageSize(pageSize);
        pageObject.setPageIndex(pageNum);
        int itemAmount = selectCountByExample(example);
        pageObject.setItemAmount(itemAmount);
        List pageList = null;
        if (pageObject.getBeginIndex() <= pageObject.getItemAmount()) {
            pageList = (getSqlMapClientTemplate().queryForList("sc_org.abatorgenerated_selectByExample", parms, pageObject.getBeginIndex() - 1, pageSize));
        }
        pageBox.setPageObject(pageObject);
        pageBox.setPageList(pageList);
        return pageBox;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(ScOrgExample example, int pageSize, int pageNum) {
        return selectByExampleWithPaging(example, pageSize, pageNum, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeyForCgs(ScOrg record) {
        int rows = getSqlMapClientTemplate().update("sc_org.abatorgenerated_updateByPrimaryKeyForCgs", record);
        return rows;
    }
}