package com.neteast.rmp.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neteast.rmp.dao.ScRoleMenuDAO;
import com.neteast.rmp.dao.domain.ScRoleMenu;
import com.neteast.rmp.dao.domain.ScRoleMenuExample;
import com.neteast.rmp.dao.ibatis.ext.BaseSqlMapClientDaoSupport;
import com.neteast.rmp.system.page.Criteria;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import com.seraph.bi.suite.support.domain.pagination.PageObject;

@Repository
public class ScRoleMenuDAOImpl extends BaseSqlMapClientDaoSupport implements ScRoleMenuDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public ScRoleMenuDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer insert(ScRoleMenu record) {
        Object newKey = getSqlMapClientTemplate().insert("sc_role_menu.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKey(ScRoleMenu record) {
        int rows = getSqlMapClientTemplate().update("sc_role_menu.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeySelective(ScRoleMenu record) {
        int rows = getSqlMapClientTemplate().update("sc_role_menu.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(ScRoleMenuExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("sc_role_menu.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(ScRoleMenuExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public ScRoleMenu selectByPrimaryKey(Integer id) {
        ScRoleMenu key = new ScRoleMenu();
        key.setId(id);
        ScRoleMenu record = (ScRoleMenu) getSqlMapClientTemplate().queryForObject("sc_role_menu.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByExample(ScRoleMenuExample example) {
        int rows = getSqlMapClientTemplate().delete("sc_role_menu.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        ScRoleMenu key = new ScRoleMenu();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("sc_role_menu.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getIDExampleParms(ScRoleMenuExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case ScRoleMenuExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NULL", "Y");
            } else {
                parms.put("AND_ID_NULL", "Y");
            }
            break;
        case ScRoleMenuExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_NULL", "Y");
            } else {
                parms.put("AND_ID_NOT_NULL", "Y");
            }
            break;
        case ScRoleMenuExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_EQUALS", "Y");
            } else {
                parms.put("AND_ID_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScRoleMenuExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ID_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScRoleMenuExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GT", "Y");
            } else {
                parms.put("AND_ID_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScRoleMenuExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GE", "Y");
            } else {
                parms.put("AND_ID_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScRoleMenuExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LT", "Y");
            } else {
                parms.put("AND_ID_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScRoleMenuExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LE", "Y");
            } else {
                parms.put("AND_ID_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getROLE_NAMEExampleParms(ScRoleMenuExample example) {
        Map parms = new HashMap();
        switch (example.getRoleName_Indicator()) {
        case ScRoleMenuExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_NULL", "Y");
            } else {
                parms.put("AND_ROLE_NAME_NULL", "Y");
            }
            break;
        case ScRoleMenuExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_NOT_NULL", "Y");
            } else {
                parms.put("AND_ROLE_NAME_NOT_NULL", "Y");
            }
            break;
        case ScRoleMenuExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_EQUALS", "Y");
            } else {
                parms.put("AND_ROLE_NAME_EQUALS", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScRoleMenuExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ROLE_NAME_NOT_EQUALS", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScRoleMenuExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_GT", "Y");
            } else {
                parms.put("AND_ROLE_NAME_GT", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScRoleMenuExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_GE", "Y");
            } else {
                parms.put("AND_ROLE_NAME_GE", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScRoleMenuExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_LT", "Y");
            } else {
                parms.put("AND_ROLE_NAME_LT", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScRoleMenuExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_LE", "Y");
            } else {
                parms.put("AND_ROLE_NAME_LE", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScRoleMenuExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_LIKE", "Y");
            } else {
                parms.put("AND_ROLE_NAME_LIKE", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getMENU_IDExampleParms(ScRoleMenuExample example) {
        Map parms = new HashMap();
        switch (example.getMenuId_Indicator()) {
        case ScRoleMenuExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_MENU_ID_NULL", "Y");
            } else {
                parms.put("AND_MENU_ID_NULL", "Y");
            }
            break;
        case ScRoleMenuExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_MENU_ID_NOT_NULL", "Y");
            } else {
                parms.put("AND_MENU_ID_NOT_NULL", "Y");
            }
            break;
        case ScRoleMenuExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_MENU_ID_EQUALS", "Y");
            } else {
                parms.put("AND_MENU_ID_EQUALS", "Y");
            }
            parms.put("menuId", example.getMenuId());
            break;
        case ScRoleMenuExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_MENU_ID_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_MENU_ID_NOT_EQUALS", "Y");
            }
            parms.put("menuId", example.getMenuId());
            break;
        case ScRoleMenuExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_MENU_ID_GT", "Y");
            } else {
                parms.put("AND_MENU_ID_GT", "Y");
            }
            parms.put("menuId", example.getMenuId());
            break;
        case ScRoleMenuExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_MENU_ID_GE", "Y");
            } else {
                parms.put("AND_MENU_ID_GE", "Y");
            }
            parms.put("menuId", example.getMenuId());
            break;
        case ScRoleMenuExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_MENU_ID_LT", "Y");
            } else {
                parms.put("AND_MENU_ID_LT", "Y");
            }
            parms.put("menuId", example.getMenuId());
            break;
        case ScRoleMenuExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_MENU_ID_LE", "Y");
            } else {
                parms.put("AND_MENU_ID_LE", "Y");
            }
            parms.put("menuId", example.getMenuId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getExampleParms(ScRoleMenuExample example) {
        Map parms = new HashMap();
        parms.putAll(getIDExampleParms(example));
        parms.putAll(getROLE_NAMEExampleParms(example));
        parms.putAll(getMENU_IDExampleParms(example));
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int selectCountByExample(ScRoleMenuExample example) {
        Map parms = getExampleParms(example);
        int count = ((Integer)getSqlMapClientTemplate().queryForObject("sc_role_menu.abatorgenerated_selectCountByExample", parms)).intValue();
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(ScRoleMenuExample example, int pageSize, int pageNum, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        PageBox pageBox = new PageBox();
        PageObject pageObject = new PageObject();
        pageObject.setPageSize(pageSize);
        pageObject.setPageIndex(pageNum);
        int itemAmount = selectCountByExample(example);
        pageObject.setItemAmount(itemAmount);
        List pageList = null;
        if (pageObject.getBeginIndex() <= pageObject.getItemAmount()) {
            pageList = (getSqlMapClientTemplate().queryForList("sc_role_menu.abatorgenerated_selectByExample", parms, pageObject.getBeginIndex() - 1, pageSize));
        }
        pageBox.setPageObject(pageObject);
        pageBox.setPageList(pageList);
        return pageBox;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(ScRoleMenuExample example, int pageSize, int pageNum) {
        return selectByExampleWithPaging(example, pageSize, pageNum, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeyForCgs(ScRoleMenu record) {
        int rows = getSqlMapClientTemplate().update("sc_role_menu.abatorgenerated_updateByPrimaryKeyForCgs", record);
        return rows;
    }

	@Override
	public List getRoleMenuInfo(Criteria c) {
		return getSqlMapClientTemplate().queryForList("sc_role_menu.getRoleMenuInfo", c.getData(), c.getStart(), c.getFetchSize());
	}

	@Override
	public Integer getRoleMenuInfoCount(Criteria c) {
		return (Integer)getSqlMapClientTemplate().queryForObject("sc_role_menu.getRoleMenuInfoCount",c.getData());
	}

	@Override
	public List getCheckedTreeNode(ScRoleMenuExample example) {
		Map parms = getExampleParms(example);
        List list = getSqlMapClientTemplate().queryForList("sc_role_menu.getCheckedTreeNode", parms);
        return list;
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<Map<String, Object>> getMenuIdsByIds(Map<String, Object> idMap) {
		return getSqlMapClientTemplate().queryForList("sc_role_menu.getMenuIdsByIds", idMap);
	}
}