package com.neteast.rmp.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.neteast.rmp.dao.ScUserRoleDAO;
import com.neteast.rmp.dao.domain.ScUserRole;
import com.neteast.rmp.dao.domain.ScUserRoleExample;
import com.neteast.rmp.dao.ibatis.ext.BaseSqlMapClientDaoSupport;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import com.seraph.bi.suite.support.domain.pagination.PageObject;

@Repository
public class ScUserRoleDAOImpl extends BaseSqlMapClientDaoSupport implements ScUserRoleDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public ScUserRoleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer insert(ScUserRole record) {
        Object newKey = getSqlMapClientTemplate().insert("sc_user_role.abatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKey(ScUserRole record) {
        int rows = getSqlMapClientTemplate().update("sc_user_role.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeySelective(ScUserRole record) {
        int rows = getSqlMapClientTemplate().update("sc_user_role.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(ScUserRoleExample example, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        List list = getSqlMapClientTemplate().queryForList("sc_user_role.abatorgenerated_selectByExample", parms);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public List selectByExample(ScUserRoleExample example) {
        return selectByExample(example, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public ScUserRole selectByPrimaryKey(Integer id) {
        ScUserRole key = new ScUserRole();
        key.setId(id);
        ScUserRole record = (ScUserRole) getSqlMapClientTemplate().queryForObject("sc_user_role.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByExample(ScUserRoleExample example) {
        int rows = getSqlMapClientTemplate().delete("sc_user_role.abatorgenerated_deleteByExample", getExampleParms(example));
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        ScUserRole key = new ScUserRole();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("sc_user_role.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getIDExampleParms(ScUserRoleExample example) {
        Map parms = new HashMap();
        switch (example.getId_Indicator()) {
        case ScUserRoleExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NULL", "Y");
            } else {
                parms.put("AND_ID_NULL", "Y");
            }
            break;
        case ScUserRoleExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_NULL", "Y");
            } else {
                parms.put("AND_ID_NOT_NULL", "Y");
            }
            break;
        case ScUserRoleExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_EQUALS", "Y");
            } else {
                parms.put("AND_ID_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScUserRoleExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ID_NOT_EQUALS", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScUserRoleExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GT", "Y");
            } else {
                parms.put("AND_ID_GT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScUserRoleExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_GE", "Y");
            } else {
                parms.put("AND_ID_GE", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScUserRoleExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LT", "Y");
            } else {
                parms.put("AND_ID_LT", "Y");
            }
            parms.put("id", example.getId());
            break;
        case ScUserRoleExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ID_LE", "Y");
            } else {
                parms.put("AND_ID_LE", "Y");
            }
            parms.put("id", example.getId());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getUSER_NAMEExampleParms(ScUserRoleExample example) {
        Map parms = new HashMap();
        switch (example.getUserName_Indicator()) {
        case ScUserRoleExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_USER_NAME_NULL", "Y");
            } else {
                parms.put("AND_USER_NAME_NULL", "Y");
            }
            break;
        case ScUserRoleExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_USER_NAME_NOT_NULL", "Y");
            } else {
                parms.put("AND_USER_NAME_NOT_NULL", "Y");
            }
            break;
        case ScUserRoleExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_USER_NAME_EQUALS", "Y");
            } else {
                parms.put("AND_USER_NAME_EQUALS", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case ScUserRoleExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_USER_NAME_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_USER_NAME_NOT_EQUALS", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case ScUserRoleExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_USER_NAME_GT", "Y");
            } else {
                parms.put("AND_USER_NAME_GT", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case ScUserRoleExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_USER_NAME_GE", "Y");
            } else {
                parms.put("AND_USER_NAME_GE", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case ScUserRoleExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_USER_NAME_LT", "Y");
            } else {
                parms.put("AND_USER_NAME_LT", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case ScUserRoleExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_USER_NAME_LE", "Y");
            } else {
                parms.put("AND_USER_NAME_LE", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        case ScUserRoleExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_USER_NAME_LIKE", "Y");
            } else {
                parms.put("AND_USER_NAME_LIKE", "Y");
            }
            parms.put("userName", example.getUserName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getROLE_NAMEExampleParms(ScUserRoleExample example) {
        Map parms = new HashMap();
        switch (example.getRoleName_Indicator()) {
        case ScUserRoleExample.EXAMPLE_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_NULL", "Y");
            } else {
                parms.put("AND_ROLE_NAME_NULL", "Y");
            }
            break;
        case ScUserRoleExample.EXAMPLE_NOT_NULL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_NOT_NULL", "Y");
            } else {
                parms.put("AND_ROLE_NAME_NOT_NULL", "Y");
            }
            break;
        case ScUserRoleExample.EXAMPLE_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_EQUALS", "Y");
            } else {
                parms.put("AND_ROLE_NAME_EQUALS", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScUserRoleExample.EXAMPLE_NOT_EQUALS:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_NOT_EQUALS", "Y");
            } else {
                parms.put("AND_ROLE_NAME_NOT_EQUALS", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScUserRoleExample.EXAMPLE_GREATER_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_GT", "Y");
            } else {
                parms.put("AND_ROLE_NAME_GT", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScUserRoleExample.EXAMPLE_GREATER_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_GE", "Y");
            } else {
                parms.put("AND_ROLE_NAME_GE", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScUserRoleExample.EXAMPLE_LESS_THAN:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_LT", "Y");
            } else {
                parms.put("AND_ROLE_NAME_LT", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScUserRoleExample.EXAMPLE_LESS_THAN_OR_EQUAL:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_LE", "Y");
            } else {
                parms.put("AND_ROLE_NAME_LE", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        case ScUserRoleExample.EXAMPLE_LIKE:
            if (example.isCombineTypeOr()) {
                parms.put("OR_ROLE_NAME_LIKE", "Y");
            } else {
                parms.put("AND_ROLE_NAME_LIKE", "Y");
            }
            parms.put("roleName", example.getRoleName());
            break;
        }
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Map getExampleParms(ScUserRoleExample example) {
        Map parms = new HashMap();
        parms.putAll(getIDExampleParms(example));
        parms.putAll(getUSER_NAMEExampleParms(example));
        parms.putAll(getROLE_NAMEExampleParms(example));
        return parms;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int selectCountByExample(ScUserRoleExample example) {
        Map parms = getExampleParms(example);
        int count = ((Integer)getSqlMapClientTemplate().queryForObject("sc_user_role.abatorgenerated_selectCountByExample", parms)).intValue();
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(ScUserRoleExample example, int pageSize, int pageNum, String orderByClause) {
        Map parms = getExampleParms(example);
        if (orderByClause != null) {
            parms.put("ABATOR_ORDER_BY_CLAUSE", orderByClause);
        }
        PageBox pageBox = new PageBox();
        PageObject pageObject = new PageObject();
        pageObject.setPageSize(pageSize);
        pageObject.setPageIndex(pageNum);
        int itemAmount = selectCountByExample(example);
        pageObject.setItemAmount(itemAmount);
        List pageList = null;
        if (pageObject.getBeginIndex() <= pageObject.getItemAmount()) {
            pageList = (getSqlMapClientTemplate().queryForList("sc_user_role.abatorgenerated_selectByExample", parms, pageObject.getBeginIndex() - 1, pageSize));
        }
        pageBox.setPageObject(pageObject);
        pageBox.setPageList(pageList);
        return pageBox;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public PageBox selectByExampleWithPaging(ScUserRoleExample example, int pageSize, int pageNum) {
        return selectByExampleWithPaging(example, pageSize, pageNum, null);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int updateByPrimaryKeyForCgs(ScUserRole record) {
        int rows = getSqlMapClientTemplate().update("sc_user_role.abatorgenerated_updateByPrimaryKeyForCgs", record);
        return rows;
    }
}