package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class RptColumnMeta {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_column_meta.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    @PrimaryKey
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_column_meta.RPT_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String rptCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_column_meta.COL_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String colName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_column_meta.COL_ALIAS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String colAlias;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_column_meta.COL_INDEX
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer colIndex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_column_meta.COL_TYPE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer colType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_column_meta.TOTAL_ENABLE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer totalEnable;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_column_meta.SUB_TOTAL_ENABLE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer subTotalEnable;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_column_meta.VISIBLE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer visible;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_column_meta.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_column_meta.ID
     *
     * @return the value of rpt_column_meta.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_column_meta.ID
     *
     * @param id the value for rpt_column_meta.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_column_meta.RPT_CODE
     *
     * @return the value of rpt_column_meta.RPT_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getRptCode() {
        return rptCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_column_meta.RPT_CODE
     *
     * @param rptCode the value for rpt_column_meta.RPT_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRptCode(String rptCode) {
        this.rptCode = rptCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_column_meta.COL_NAME
     *
     * @return the value of rpt_column_meta.COL_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getColName() {
        return colName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_column_meta.COL_NAME
     *
     * @param colName the value for rpt_column_meta.COL_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setColName(String colName) {
        this.colName = colName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_column_meta.COL_ALIAS
     *
     * @return the value of rpt_column_meta.COL_ALIAS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getColAlias() {
        return colAlias;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_column_meta.COL_ALIAS
     *
     * @param colAlias the value for rpt_column_meta.COL_ALIAS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setColAlias(String colAlias) {
        this.colAlias = colAlias;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_column_meta.COL_INDEX
     *
     * @return the value of rpt_column_meta.COL_INDEX
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getColIndex() {
        return colIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_column_meta.COL_INDEX
     *
     * @param colIndex the value for rpt_column_meta.COL_INDEX
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setColIndex(Integer colIndex) {
        this.colIndex = colIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_column_meta.COL_TYPE
     *
     * @return the value of rpt_column_meta.COL_TYPE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getColType() {
        return colType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_column_meta.COL_TYPE
     *
     * @param colType the value for rpt_column_meta.COL_TYPE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setColType(Integer colType) {
        this.colType = colType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_column_meta.TOTAL_ENABLE
     *
     * @return the value of rpt_column_meta.TOTAL_ENABLE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getTotalEnable() {
        return totalEnable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_column_meta.TOTAL_ENABLE
     *
     * @param totalEnable the value for rpt_column_meta.TOTAL_ENABLE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setTotalEnable(Integer totalEnable) {
        this.totalEnable = totalEnable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_column_meta.SUB_TOTAL_ENABLE
     *
     * @return the value of rpt_column_meta.SUB_TOTAL_ENABLE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getSubTotalEnable() {
        return subTotalEnable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_column_meta.SUB_TOTAL_ENABLE
     *
     * @param subTotalEnable the value for rpt_column_meta.SUB_TOTAL_ENABLE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setSubTotalEnable(Integer subTotalEnable) {
        this.subTotalEnable = subTotalEnable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_column_meta.VISIBLE
     *
     * @return the value of rpt_column_meta.VISIBLE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getVisible() {
        return visible;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_column_meta.VISIBLE
     *
     * @param visible the value for rpt_column_meta.VISIBLE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setVisible(Integer visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_column_meta.ID
     *
     * @return the value of rpt_column_meta.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_column_meta.ID
     *
     * @param id_old the value for rpt_column_meta.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_old(Integer id_old) {
        this.id_old = id_old;
    }
}