package com.neteast.rmp.dao.domain;

public class RptFormulaExample extends RptFormula {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int rptCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int rowIndex_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int colIndex_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int rptFormula_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getRptCode_Indicator() {
        return rptCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRptCode_Indicator(int rptCode_Indicator) {
        this.rptCode_Indicator = rptCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getRowIndex_Indicator() {
        return rowIndex_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRowIndex_Indicator(int rowIndex_Indicator) {
        this.rowIndex_Indicator = rowIndex_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getColIndex_Indicator() {
        return colIndex_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setColIndex_Indicator(int colIndex_Indicator) {
        this.colIndex_Indicator = colIndex_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getRptFormula_Indicator() {
        return rptFormula_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_formula
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRptFormula_Indicator(int rptFormula_Indicator) {
        this.rptFormula_Indicator = rptFormula_Indicator;
    }
}