package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class RptFormula {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_formula.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    @PrimaryKey
    private Double id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_formula.RPT_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String rptCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_formula.ROW_INDEX
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer rowIndex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_formula.COL_INDEX
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer colIndex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_formula.RPT_FORMULA
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String rptFormula;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_formula.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Double id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_formula.ID
     *
     * @return the value of rpt_formula.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Double getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_formula.ID
     *
     * @param id the value for rpt_formula.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId(Double id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_formula.RPT_CODE
     *
     * @return the value of rpt_formula.RPT_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getRptCode() {
        return rptCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_formula.RPT_CODE
     *
     * @param rptCode the value for rpt_formula.RPT_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRptCode(String rptCode) {
        this.rptCode = rptCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_formula.ROW_INDEX
     *
     * @return the value of rpt_formula.ROW_INDEX
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getRowIndex() {
        return rowIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_formula.ROW_INDEX
     *
     * @param rowIndex the value for rpt_formula.ROW_INDEX
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRowIndex(Integer rowIndex) {
        this.rowIndex = rowIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_formula.COL_INDEX
     *
     * @return the value of rpt_formula.COL_INDEX
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getColIndex() {
        return colIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_formula.COL_INDEX
     *
     * @param colIndex the value for rpt_formula.COL_INDEX
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setColIndex(Integer colIndex) {
        this.colIndex = colIndex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_formula.RPT_FORMULA
     *
     * @return the value of rpt_formula.RPT_FORMULA
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getRptFormula() {
        return rptFormula;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_formula.RPT_FORMULA
     *
     * @param rptFormula the value for rpt_formula.RPT_FORMULA
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRptFormula(String rptFormula) {
        this.rptFormula = rptFormula;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_formula.ID
     *
     * @return the value of rpt_formula.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Double getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_formula.ID
     *
     * @param id_old the value for rpt_formula.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_old(Double id_old) {
        this.id_old = id_old;
    }
}