package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;
import java.util.Date;

public class RptInstance {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    @PrimaryKey
    private Double id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.RPT_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String rptCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String orgCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.RPT_DATE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Date rptDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.RPT_STATUS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer rptStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.AUDIT_STATUS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer auditStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.AUDIT_DATE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Date auditDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.AUDIT_USER_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String auditUserName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.AUDIT_USER_ALIAS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String auditUserAlias;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.AUDIT_MSG
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String auditMsg;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.LOCKED
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer locked;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column rpt_instance.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Double id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.ID
     *
     * @return the value of rpt_instance.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Double getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.ID
     *
     * @param id the value for rpt_instance.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId(Double id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.RPT_CODE
     *
     * @return the value of rpt_instance.RPT_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getRptCode() {
        return rptCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.RPT_CODE
     *
     * @param rptCode the value for rpt_instance.RPT_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRptCode(String rptCode) {
        this.rptCode = rptCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.ORG_CODE
     *
     * @return the value of rpt_instance.ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.ORG_CODE
     *
     * @param orgCode the value for rpt_instance.ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.RPT_DATE
     *
     * @return the value of rpt_instance.RPT_DATE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Date getRptDate() {
        return rptDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.RPT_DATE
     *
     * @param rptDate the value for rpt_instance.RPT_DATE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRptDate(Date rptDate) {
        this.rptDate = rptDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.RPT_STATUS
     *
     * @return the value of rpt_instance.RPT_STATUS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getRptStatus() {
        return rptStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.RPT_STATUS
     *
     * @param rptStatus the value for rpt_instance.RPT_STATUS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRptStatus(Integer rptStatus) {
        this.rptStatus = rptStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.AUDIT_STATUS
     *
     * @return the value of rpt_instance.AUDIT_STATUS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.AUDIT_STATUS
     *
     * @param auditStatus the value for rpt_instance.AUDIT_STATUS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.AUDIT_DATE
     *
     * @return the value of rpt_instance.AUDIT_DATE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Date getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.AUDIT_DATE
     *
     * @param auditDate the value for rpt_instance.AUDIT_DATE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.AUDIT_USER_NAME
     *
     * @return the value of rpt_instance.AUDIT_USER_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getAuditUserName() {
        return auditUserName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.AUDIT_USER_NAME
     *
     * @param auditUserName the value for rpt_instance.AUDIT_USER_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setAuditUserName(String auditUserName) {
        this.auditUserName = auditUserName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.AUDIT_USER_ALIAS
     *
     * @return the value of rpt_instance.AUDIT_USER_ALIAS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getAuditUserAlias() {
        return auditUserAlias;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.AUDIT_USER_ALIAS
     *
     * @param auditUserAlias the value for rpt_instance.AUDIT_USER_ALIAS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setAuditUserAlias(String auditUserAlias) {
        this.auditUserAlias = auditUserAlias;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.AUDIT_MSG
     *
     * @return the value of rpt_instance.AUDIT_MSG
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getAuditMsg() {
        return auditMsg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.AUDIT_MSG
     *
     * @param auditMsg the value for rpt_instance.AUDIT_MSG
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setAuditMsg(String auditMsg) {
        this.auditMsg = auditMsg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.LOCKED
     *
     * @return the value of rpt_instance.LOCKED
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getLocked() {
        return locked;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.LOCKED
     *
     * @param locked the value for rpt_instance.LOCKED
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column rpt_instance.ID
     *
     * @return the value of rpt_instance.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Double getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column rpt_instance.ID
     *
     * @param id_old the value for rpt_instance.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_old(Double id_old) {
        this.id_old = id_old;
    }
}