package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class ScGlobalParm {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_global_parm.ID
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    @PrimaryKey
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_global_parm.PARM_CODE
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    private String parmCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_global_parm.PARM_NAME
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    private String parmName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_global_parm.PARM_VALUE
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    private String parmValue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_global_parm.DESCRIPTION
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    private String description;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_global_parm.ID
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    private Integer id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_global_parm.ID
     *
     * @return the value of sc_global_parm.ID
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_global_parm.ID
     *
     * @param id the value for sc_global_parm.ID
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_global_parm.PARM_CODE
     *
     * @return the value of sc_global_parm.PARM_CODE
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public String getParmCode() {
        return parmCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_global_parm.PARM_CODE
     *
     * @param parmCode the value for sc_global_parm.PARM_CODE
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public void setParmCode(String parmCode) {
        this.parmCode = parmCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_global_parm.PARM_NAME
     *
     * @return the value of sc_global_parm.PARM_NAME
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public String getParmName() {
        return parmName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_global_parm.PARM_NAME
     *
     * @param parmName the value for sc_global_parm.PARM_NAME
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public void setParmName(String parmName) {
        this.parmName = parmName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_global_parm.PARM_VALUE
     *
     * @return the value of sc_global_parm.PARM_VALUE
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public String getParmValue() {
        return parmValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_global_parm.PARM_VALUE
     *
     * @param parmValue the value for sc_global_parm.PARM_VALUE
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public void setParmValue(String parmValue) {
        this.parmValue = parmValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_global_parm.DESCRIPTION
     *
     * @return the value of sc_global_parm.DESCRIPTION
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_global_parm.DESCRIPTION
     *
     * @param description the value for sc_global_parm.DESCRIPTION
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_global_parm.ID
     *
     * @return the value of sc_global_parm.ID
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public Integer getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_global_parm.ID
     *
     * @param id_old the value for sc_global_parm.ID
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public void setId_old(Integer id_old) {
        this.id_old = id_old;
    }
}