package com.neteast.rmp.dao.domain;

public class ScHomepageCfg {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_homepage_cfg.ID
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_homepage_cfg.TITLE
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_homepage_cfg.HREF
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    private String href;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_homepage_cfg.ROW_NUM
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    private Integer rowNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_homepage_cfg.COL_NUM
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    private Integer colNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_homepage_cfg.SORT
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    private Integer sort;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_homepage_cfg.DESCRIPTION
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    private String description;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_homepage_cfg.ID
     *
     * @return the value of sc_homepage_cfg.ID
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_homepage_cfg.ID
     *
     * @param id the value for sc_homepage_cfg.ID
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_homepage_cfg.TITLE
     *
     * @return the value of sc_homepage_cfg.TITLE
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_homepage_cfg.TITLE
     *
     * @param title the value for sc_homepage_cfg.TITLE
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_homepage_cfg.HREF
     *
     * @return the value of sc_homepage_cfg.HREF
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_homepage_cfg.HREF
     *
     * @param href the value for sc_homepage_cfg.HREF
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_homepage_cfg.ROW_NUM
     *
     * @return the value of sc_homepage_cfg.ROW_NUM
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public Integer getRowNum() {
        return rowNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_homepage_cfg.ROW_NUM
     *
     * @param rowNum the value for sc_homepage_cfg.ROW_NUM
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public void setRowNum(Integer rowNum) {
        this.rowNum = rowNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_homepage_cfg.COL_NUM
     *
     * @return the value of sc_homepage_cfg.COL_NUM
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public Integer getColNum() {
        return colNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_homepage_cfg.COL_NUM
     *
     * @param colNum the value for sc_homepage_cfg.COL_NUM
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public void setColNum(Integer colNum) {
        this.colNum = colNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_homepage_cfg.SORT
     *
     * @return the value of sc_homepage_cfg.SORT
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_homepage_cfg.SORT
     *
     * @param sort the value for sc_homepage_cfg.SORT
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_homepage_cfg.DESCRIPTION
     *
     * @return the value of sc_homepage_cfg.DESCRIPTION
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_homepage_cfg.DESCRIPTION
     *
     * @param description the value for sc_homepage_cfg.DESCRIPTION
     *
     * @abatorgenerated Tue Nov 06 14:43:17 CST 2012
     */
    public void setDescription(String description) {
        this.description = description;
    }
}