package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class ScOrg {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    @PrimaryKey
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org.ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String orgCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org.ORG_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String orgName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org.ORG_SHORT_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String orgShortName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org.ORG_LEVEL
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer orgLevel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org.ID
     *
     * @return the value of sc_org.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org.ID
     *
     * @param id the value for sc_org.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org.ORG_CODE
     *
     * @return the value of sc_org.ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org.ORG_CODE
     *
     * @param orgCode the value for sc_org.ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org.ORG_NAME
     *
     * @return the value of sc_org.ORG_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org.ORG_NAME
     *
     * @param orgName the value for sc_org.ORG_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org.ORG_SHORT_NAME
     *
     * @return the value of sc_org.ORG_SHORT_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getOrgShortName() {
        return orgShortName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org.ORG_SHORT_NAME
     *
     * @param orgShortName the value for sc_org.ORG_SHORT_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setOrgShortName(String orgShortName) {
        this.orgShortName = orgShortName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org.ORG_LEVEL
     *
     * @return the value of sc_org.ORG_LEVEL
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org.ORG_LEVEL
     *
     * @param orgLevel the value for sc_org.ORG_LEVEL
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setOrgLevel(Integer orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org.ID
     *
     * @return the value of sc_org.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org.ID
     *
     * @param id_old the value for sc_org.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_old(Integer id_old) {
        this.id_old = id_old;
    }
}