package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class ScOrgSeq {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org_seq.ORG_CODE
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    @PrimaryKey
    private String orgCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org_seq.CUR_SEQ
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    private Integer curSeq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org_seq.ORG_CODE
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    private String orgCode_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org_seq.ORG_CODE
     *
     * @return the value of sc_org_seq.ORG_CODE
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org_seq.ORG_CODE
     *
     * @param orgCode the value for sc_org_seq.ORG_CODE
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org_seq.CUR_SEQ
     *
     * @return the value of sc_org_seq.CUR_SEQ
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public Integer getCurSeq() {
        return curSeq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org_seq.CUR_SEQ
     *
     * @param curSeq the value for sc_org_seq.CUR_SEQ
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public void setCurSeq(Integer curSeq) {
        this.curSeq = curSeq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org_seq.ORG_CODE
     *
     * @return the value of sc_org_seq.ORG_CODE
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public String getOrgCode_old() {
        return orgCode_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org_seq.ORG_CODE
     *
     * @param orgCode_old the value for sc_org_seq.ORG_CODE
     *
     * @abatorgenerated Wed Oct 19 14:49:28 CST 2011
     */
    public void setOrgCode_old(String orgCode_old) {
        this.orgCode_old = orgCode_old;
    }
}