package com.neteast.rmp.dao.domain;

public class ScOrgSeqExample extends ScOrgSeq {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    private int orgCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    private int curSeq_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public int getOrgCode_Indicator() {
        return orgCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public void setOrgCode_Indicator(int orgCode_Indicator) {
        this.orgCode_Indicator = orgCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public int getCurSeq_Indicator() {
        return curSeq_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    public void setCurSeq_Indicator(int curSeq_Indicator) {
        this.curSeq_Indicator = curSeq_Indicator;
    }
}