package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class ScOrgRelation {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org_relation.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    @PrimaryKey
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org_relation.CURR_ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String currOrgCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org_relation.PARENT_ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String parentOrgCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org_relation.LEAF_SIGN
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer leafSign;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_org_relation.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org_relation.ID
     *
     * @return the value of sc_org_relation.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org_relation.ID
     *
     * @param id the value for sc_org_relation.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org_relation.CURR_ORG_CODE
     *
     * @return the value of sc_org_relation.CURR_ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getCurrOrgCode() {
        return currOrgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org_relation.CURR_ORG_CODE
     *
     * @param currOrgCode the value for sc_org_relation.CURR_ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setCurrOrgCode(String currOrgCode) {
        this.currOrgCode = currOrgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org_relation.PARENT_ORG_CODE
     *
     * @return the value of sc_org_relation.PARENT_ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getParentOrgCode() {
        return parentOrgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org_relation.PARENT_ORG_CODE
     *
     * @param parentOrgCode the value for sc_org_relation.PARENT_ORG_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setParentOrgCode(String parentOrgCode) {
        this.parentOrgCode = parentOrgCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org_relation.LEAF_SIGN
     *
     * @return the value of sc_org_relation.LEAF_SIGN
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getLeafSign() {
        return leafSign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org_relation.LEAF_SIGN
     *
     * @param leafSign the value for sc_org_relation.LEAF_SIGN
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setLeafSign(Integer leafSign) {
        this.leafSign = leafSign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_org_relation.ID
     *
     * @return the value of sc_org_relation.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_org_relation.ID
     *
     * @param id_old the value for sc_org_relation.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_old(Integer id_old) {
        this.id_old = id_old;
    }
}