package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class ScParmInfo {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_info.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    @PrimaryKey
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_info.PARM_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String parmCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_info.PARM_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String parmName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_info.TYPE_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String typeCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_info.PARM_SORT
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer parmSort;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_info.DESCRIPTION
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String description;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_info.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_info.ID
     *
     * @return the value of sc_parm_info.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_info.ID
     *
     * @param id the value for sc_parm_info.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_info.PARM_CODE
     *
     * @return the value of sc_parm_info.PARM_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getParmCode() {
        return parmCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_info.PARM_CODE
     *
     * @param parmCode the value for sc_parm_info.PARM_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setParmCode(String parmCode) {
        this.parmCode = parmCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_info.PARM_NAME
     *
     * @return the value of sc_parm_info.PARM_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getParmName() {
        return parmName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_info.PARM_NAME
     *
     * @param parmName the value for sc_parm_info.PARM_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setParmName(String parmName) {
        this.parmName = parmName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_info.TYPE_CODE
     *
     * @return the value of sc_parm_info.TYPE_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_info.TYPE_CODE
     *
     * @param typeCode the value for sc_parm_info.TYPE_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_info.PARM_SORT
     *
     * @return the value of sc_parm_info.PARM_SORT
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getParmSort() {
        return parmSort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_info.PARM_SORT
     *
     * @param parmSort the value for sc_parm_info.PARM_SORT
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setParmSort(Integer parmSort) {
        this.parmSort = parmSort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_info.DESCRIPTION
     *
     * @return the value of sc_parm_info.DESCRIPTION
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_info.DESCRIPTION
     *
     * @param description the value for sc_parm_info.DESCRIPTION
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_info.ID
     *
     * @return the value of sc_parm_info.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_info.ID
     *
     * @param id_old the value for sc_parm_info.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_old(Integer id_old) {
        this.id_old = id_old;
    }
}