package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class ScParmType {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_type.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    @PrimaryKey
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_type.TYPE_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String typeCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_type.TYPE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String typeName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_type.SYSTEM_SIGN
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer systemSign;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_parm_type.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_type.ID
     *
     * @return the value of sc_parm_type.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_type.ID
     *
     * @param id the value for sc_parm_type.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_type.TYPE_CODE
     *
     * @return the value of sc_parm_type.TYPE_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_type.TYPE_CODE
     *
     * @param typeCode the value for sc_parm_type.TYPE_CODE
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_type.TYPE_NAME
     *
     * @return the value of sc_parm_type.TYPE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_type.TYPE_NAME
     *
     * @param typeName the value for sc_parm_type.TYPE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_type.SYSTEM_SIGN
     *
     * @return the value of sc_parm_type.SYSTEM_SIGN
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getSystemSign() {
        return systemSign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_type.SYSTEM_SIGN
     *
     * @param systemSign the value for sc_parm_type.SYSTEM_SIGN
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setSystemSign(Integer systemSign) {
        this.systemSign = systemSign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_parm_type.ID
     *
     * @return the value of sc_parm_type.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_parm_type.ID
     *
     * @param id_old the value for sc_parm_type.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_old(Integer id_old) {
        this.id_old = id_old;
    }
}