package com.neteast.rmp.dao.domain;

public class ScParmTypeExample extends ScParmType {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int typeCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int typeName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int systemSign_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getTypeCode_Indicator() {
        return typeCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setTypeCode_Indicator(int typeCode_Indicator) {
        this.typeCode_Indicator = typeCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getTypeName_Indicator() {
        return typeName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setTypeName_Indicator(int typeName_Indicator) {
        this.typeName_Indicator = typeName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getSystemSign_Indicator() {
        return systemSign_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_type
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setSystemSign_Indicator(int systemSign_Indicator) {
        this.systemSign_Indicator = systemSign_Indicator;
    }
}