package com.neteast.rmp.dao.domain;

public class ScParmInfoExample extends ScParmInfo {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int parmCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int parmName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int typeCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int parmSort_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int description_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getParmCode_Indicator() {
        return parmCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setParmCode_Indicator(int parmCode_Indicator) {
        this.parmCode_Indicator = parmCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getParmName_Indicator() {
        return parmName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setParmName_Indicator(int parmName_Indicator) {
        this.parmName_Indicator = parmName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getTypeCode_Indicator() {
        return typeCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setTypeCode_Indicator(int typeCode_Indicator) {
        this.typeCode_Indicator = typeCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getParmSort_Indicator() {
        return parmSort_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setParmSort_Indicator(int parmSort_Indicator) {
        this.parmSort_Indicator = parmSort_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getDescription_Indicator() {
        return description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_parm_info
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setDescription_Indicator(int description_Indicator) {
        this.description_Indicator = description_Indicator;
    }
}