package com.neteast.rmp.dao.domain;

public class ScPortalGlobalParmsExample extends ScPortalGlobalParms {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    private int parmCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    private int parmName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    private int parmType_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    private int parmValue_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    private int dicUrl_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    private int dicDisplayField_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    private int dicValueField_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    private int description_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public int getParmCode_Indicator() {
        return parmCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public void setParmCode_Indicator(int parmCode_Indicator) {
        this.parmCode_Indicator = parmCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public int getParmName_Indicator() {
        return parmName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public void setParmName_Indicator(int parmName_Indicator) {
        this.parmName_Indicator = parmName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public int getParmType_Indicator() {
        return parmType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public void setParmType_Indicator(int parmType_Indicator) {
        this.parmType_Indicator = parmType_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public int getParmValue_Indicator() {
        return parmValue_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public void setParmValue_Indicator(int parmValue_Indicator) {
        this.parmValue_Indicator = parmValue_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public int getDicUrl_Indicator() {
        return dicUrl_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public void setDicUrl_Indicator(int dicUrl_Indicator) {
        this.dicUrl_Indicator = dicUrl_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public int getDicDisplayField_Indicator() {
        return dicDisplayField_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public void setDicDisplayField_Indicator(int dicDisplayField_Indicator) {
        this.dicDisplayField_Indicator = dicDisplayField_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public int getDicValueField_Indicator() {
        return dicValueField_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public void setDicValueField_Indicator(int dicValueField_Indicator) {
        this.dicValueField_Indicator = dicValueField_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public int getDescription_Indicator() {
        return description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_global_parms
     *
     * @abatorgenerated Mon Apr 08 20:00:15 CST 2013
     */
    public void setDescription_Indicator(int description_Indicator) {
        this.description_Indicator = description_Indicator;
    }
}