package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class ScPortalParms {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.ID
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    @PrimaryKey
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.PORTAL_CODE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private String portalCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.PARM_CODE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private String parmCode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.PARM_NAME
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private String parmName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.PARM_TYPE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private Integer parmType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.PARM_VALUE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private String parmValue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.DIC_URL
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private String dicUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.DIC_DISPLAY_FIELD
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private String dicDisplayField;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.DIC_VALUE_FIELD
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private String dicValueField;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.SORT
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private Integer sort;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.DESCRIPTION
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private String description;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_portal_parms.ID
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    private Integer id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.ID
     *
     * @return the value of sc_portal_parms.ID
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.ID
     *
     * @param id the value for sc_portal_parms.ID
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.PORTAL_CODE
     *
     * @return the value of sc_portal_parms.PORTAL_CODE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public String getPortalCode() {
        return portalCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.PORTAL_CODE
     *
     * @param portalCode the value for sc_portal_parms.PORTAL_CODE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setPortalCode(String portalCode) {
        this.portalCode = portalCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.PARM_CODE
     *
     * @return the value of sc_portal_parms.PARM_CODE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public String getParmCode() {
        return parmCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.PARM_CODE
     *
     * @param parmCode the value for sc_portal_parms.PARM_CODE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setParmCode(String parmCode) {
        this.parmCode = parmCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.PARM_NAME
     *
     * @return the value of sc_portal_parms.PARM_NAME
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public String getParmName() {
        return parmName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.PARM_NAME
     *
     * @param parmName the value for sc_portal_parms.PARM_NAME
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setParmName(String parmName) {
        this.parmName = parmName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.PARM_TYPE
     *
     * @return the value of sc_portal_parms.PARM_TYPE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public Integer getParmType() {
        return parmType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.PARM_TYPE
     *
     * @param parmType the value for sc_portal_parms.PARM_TYPE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setParmType(Integer parmType) {
        this.parmType = parmType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.PARM_VALUE
     *
     * @return the value of sc_portal_parms.PARM_VALUE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public String getParmValue() {
        return parmValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.PARM_VALUE
     *
     * @param parmValue the value for sc_portal_parms.PARM_VALUE
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setParmValue(String parmValue) {
        this.parmValue = parmValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.DIC_URL
     *
     * @return the value of sc_portal_parms.DIC_URL
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public String getDicUrl() {
        return dicUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.DIC_URL
     *
     * @param dicUrl the value for sc_portal_parms.DIC_URL
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setDicUrl(String dicUrl) {
        this.dicUrl = dicUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.DIC_DISPLAY_FIELD
     *
     * @return the value of sc_portal_parms.DIC_DISPLAY_FIELD
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public String getDicDisplayField() {
        return dicDisplayField;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.DIC_DISPLAY_FIELD
     *
     * @param dicDisplayField the value for sc_portal_parms.DIC_DISPLAY_FIELD
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setDicDisplayField(String dicDisplayField) {
        this.dicDisplayField = dicDisplayField;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.DIC_VALUE_FIELD
     *
     * @return the value of sc_portal_parms.DIC_VALUE_FIELD
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public String getDicValueField() {
        return dicValueField;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.DIC_VALUE_FIELD
     *
     * @param dicValueField the value for sc_portal_parms.DIC_VALUE_FIELD
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setDicValueField(String dicValueField) {
        this.dicValueField = dicValueField;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.SORT
     *
     * @return the value of sc_portal_parms.SORT
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.SORT
     *
     * @param sort the value for sc_portal_parms.SORT
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.DESCRIPTION
     *
     * @return the value of sc_portal_parms.DESCRIPTION
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.DESCRIPTION
     *
     * @param description the value for sc_portal_parms.DESCRIPTION
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_portal_parms.ID
     *
     * @return the value of sc_portal_parms.ID
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public Integer getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_portal_parms.ID
     *
     * @param id_old the value for sc_portal_parms.ID
     *
     * @abatorgenerated Mon Apr 08 19:59:23 CST 2013
     */
    public void setId_old(Integer id_old) {
        this.id_old = id_old;
    }
}