package com.neteast.rmp.dao.domain;

public class ScPortalStyExample extends ScPortalSty {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    private int portalCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    private int portalTitle_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    private int columnCount_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    private int cellWidth_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    private int cellHeight_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    private int scrollWidth_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    private int padding_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public int getPortalCode_Indicator() {
        return portalCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public void setPortalCode_Indicator(int portalCode_Indicator) {
        this.portalCode_Indicator = portalCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public int getPortalTitle_Indicator() {
        return portalTitle_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public void setPortalTitle_Indicator(int portalTitle_Indicator) {
        this.portalTitle_Indicator = portalTitle_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public int getColumnCount_Indicator() {
        return columnCount_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public void setColumnCount_Indicator(int columnCount_Indicator) {
        this.columnCount_Indicator = columnCount_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public int getCellWidth_Indicator() {
        return cellWidth_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public void setCellWidth_Indicator(int cellWidth_Indicator) {
        this.cellWidth_Indicator = cellWidth_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public int getCellHeight_Indicator() {
        return cellHeight_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public void setCellHeight_Indicator(int cellHeight_Indicator) {
        this.cellHeight_Indicator = cellHeight_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public int getScrollWidth_Indicator() {
        return scrollWidth_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public void setScrollWidth_Indicator(int scrollWidth_Indicator) {
        this.scrollWidth_Indicator = scrollWidth_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public int getPadding_Indicator() {
        return padding_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_sty
     *
     * @abatorgenerated Sun Apr 07 19:51:43 CST 2013
     */
    public void setPadding_Indicator(int padding_Indicator) {
        this.padding_Indicator = padding_Indicator;
    }
}