package com.neteast.rmp.dao.domain;

public class ScPortalCfgExample extends ScPortalCfg {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    private int portalCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    private int title_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    private int href_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    private int rowNum_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    private int colNum_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    private int sort_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    private int description_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public int getPortalCode_Indicator() {
        return portalCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public void setPortalCode_Indicator(int portalCode_Indicator) {
        this.portalCode_Indicator = portalCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public int getTitle_Indicator() {
        return title_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public void setTitle_Indicator(int title_Indicator) {
        this.title_Indicator = title_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public int getHref_Indicator() {
        return href_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public void setHref_Indicator(int href_Indicator) {
        this.href_Indicator = href_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public int getRowNum_Indicator() {
        return rowNum_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public void setRowNum_Indicator(int rowNum_Indicator) {
        this.rowNum_Indicator = rowNum_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public int getColNum_Indicator() {
        return colNum_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public void setColNum_Indicator(int colNum_Indicator) {
        this.colNum_Indicator = colNum_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public int getSort_Indicator() {
        return sort_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public void setSort_Indicator(int sort_Indicator) {
        this.sort_Indicator = sort_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public int getDescription_Indicator() {
        return description_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_portal_cfg
     *
     * @abatorgenerated Tue Nov 06 18:51:05 CST 2012
     */
    public void setDescription_Indicator(int description_Indicator) {
        this.description_Indicator = description_Indicator;
    }
}