package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class ScRoleMenu {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_role_menu.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    @PrimaryKey
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_role_menu.ROLE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String roleName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_role_menu.MENU_ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer menuId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_role_menu.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_role_menu.ID
     *
     * @return the value of sc_role_menu.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_role_menu.ID
     *
     * @param id the value for sc_role_menu.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_role_menu.ROLE_NAME
     *
     * @return the value of sc_role_menu.ROLE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_role_menu.ROLE_NAME
     *
     * @param roleName the value for sc_role_menu.ROLE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_role_menu.MENU_ID
     *
     * @return the value of sc_role_menu.MENU_ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_role_menu.MENU_ID
     *
     * @param menuId the value for sc_role_menu.MENU_ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_role_menu.ID
     *
     * @return the value of sc_role_menu.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_role_menu.ID
     *
     * @param id_old the value for sc_role_menu.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_old(Integer id_old) {
        this.id_old = id_old;
    }
}