package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class ScRole {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    @PrimaryKey
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_role.ROLE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String roleName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_role.ROLE_ALIAS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String roleAlias;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_role.DESCRIPTION
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private String description;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private Integer id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_role.ID
     *
     * @return the value of sc_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_role.ID
     *
     * @param id the value for sc_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_role.ROLE_NAME
     *
     * @return the value of sc_role.ROLE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_role.ROLE_NAME
     *
     * @param roleName the value for sc_role.ROLE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_role.ROLE_ALIAS
     *
     * @return the value of sc_role.ROLE_ALIAS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getRoleAlias() {
        return roleAlias;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_role.ROLE_ALIAS
     *
     * @param roleAlias the value for sc_role.ROLE_ALIAS
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRoleAlias(String roleAlias) {
        this.roleAlias = roleAlias;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_role.DESCRIPTION
     *
     * @return the value of sc_role.DESCRIPTION
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_role.DESCRIPTION
     *
     * @param description the value for sc_role.DESCRIPTION
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_role.ID
     *
     * @return the value of sc_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public Integer getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_role.ID
     *
     * @param id_old the value for sc_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_old(Integer id_old) {
        this.id_old = id_old;
    }
}