package com.neteast.rmp.dao.domain;

public class ScRoleOptExample extends ScRoleOpt {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int roleName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int optCode_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getRoleName_Indicator() {
        return roleName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setRoleName_Indicator(int roleName_Indicator) {
        this.roleName_Indicator = roleName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getOptCode_Indicator() {
        return optCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_opt
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setOptCode_Indicator(int optCode_Indicator) {
        this.optCode_Indicator = optCode_Indicator;
    }
}