package com.neteast.rmp.dao.domain;

public class ScTreeMenuExample extends ScTreeMenu {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int menuId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int parentId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int text_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int leaf_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int disabled_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int cls_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int iconCls_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int href_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int visibility_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int type_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int sort_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int hrefTarget_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getMenuId_Indicator() {
        return menuId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setMenuId_Indicator(int menuId_Indicator) {
        this.menuId_Indicator = menuId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getParentId_Indicator() {
        return parentId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setParentId_Indicator(int parentId_Indicator) {
        this.parentId_Indicator = parentId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getText_Indicator() {
        return text_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setText_Indicator(int text_Indicator) {
        this.text_Indicator = text_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getLeaf_Indicator() {
        return leaf_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setLeaf_Indicator(int leaf_Indicator) {
        this.leaf_Indicator = leaf_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getDisabled_Indicator() {
        return disabled_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setDisabled_Indicator(int disabled_Indicator) {
        this.disabled_Indicator = disabled_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getCls_Indicator() {
        return cls_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setCls_Indicator(int cls_Indicator) {
        this.cls_Indicator = cls_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getIconCls_Indicator() {
        return iconCls_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setIconCls_Indicator(int iconCls_Indicator) {
        this.iconCls_Indicator = iconCls_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getHref_Indicator() {
        return href_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setHref_Indicator(int href_Indicator) {
        this.href_Indicator = href_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getVisibility_Indicator() {
        return visibility_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setVisibility_Indicator(int visibility_Indicator) {
        this.visibility_Indicator = visibility_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getType_Indicator() {
        return type_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setType_Indicator(int type_Indicator) {
        this.type_Indicator = type_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getSort_Indicator() {
        return sort_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setSort_Indicator(int sort_Indicator) {
        this.sort_Indicator = sort_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getHrefTarget_Indicator() {
        return hrefTarget_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setHrefTarget_Indicator(int hrefTarget_Indicator) {
        this.hrefTarget_Indicator = hrefTarget_Indicator;
    }
}