package com.neteast.rmp.dao.domain;

import com.seraph.bi.suite.support.domain.annotations.PrimaryKey;

public class ScUserRole {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_user_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    @PrimaryKey
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_user_role.USER_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    private String userName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_user_role.ROLE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    private String roleName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sc_user_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    private Integer id_old;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_user_role.ID
     *
     * @return the value of sc_user_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_user_role.ID
     *
     * @param id the value for sc_user_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_user_role.USER_NAME
     *
     * @return the value of sc_user_role.USER_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_user_role.USER_NAME
     *
     * @param userName the value for sc_user_role.USER_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_user_role.ROLE_NAME
     *
     * @return the value of sc_user_role.ROLE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_user_role.ROLE_NAME
     *
     * @param roleName the value for sc_user_role.ROLE_NAME
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sc_user_role.ID
     *
     * @return the value of sc_user_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    public Integer getId_old() {
        return id_old;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sc_user_role.ID
     *
     * @param id_old the value for sc_user_role.ID
     *
     * @abatorgenerated Tue Sep 20 22:24:45 CST 2011
     */
    public void setId_old(Integer id_old) {
        this.id_old = id_old;
    }
}