package com.neteast.rmp.dao.domain;

public class ScUserExample extends ScUser {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int userId_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int userName_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int orgCode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int userAlias_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int password_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int cellphoneNum_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int phoneNum_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int email_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int startDate_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int endDate_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int accountEnabled_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int accountExpired_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int accountLocked_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    private int credentialsExpired_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getUserId_Indicator() {
        return userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setUserId_Indicator(int userId_Indicator) {
        this.userId_Indicator = userId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getUserName_Indicator() {
        return userName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setUserName_Indicator(int userName_Indicator) {
        this.userName_Indicator = userName_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getOrgCode_Indicator() {
        return orgCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setOrgCode_Indicator(int orgCode_Indicator) {
        this.orgCode_Indicator = orgCode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getUserAlias_Indicator() {
        return userAlias_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setUserAlias_Indicator(int userAlias_Indicator) {
        this.userAlias_Indicator = userAlias_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getPassword_Indicator() {
        return password_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setPassword_Indicator(int password_Indicator) {
        this.password_Indicator = password_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getCellphoneNum_Indicator() {
        return cellphoneNum_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setCellphoneNum_Indicator(int cellphoneNum_Indicator) {
        this.cellphoneNum_Indicator = cellphoneNum_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getPhoneNum_Indicator() {
        return phoneNum_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setPhoneNum_Indicator(int phoneNum_Indicator) {
        this.phoneNum_Indicator = phoneNum_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getEmail_Indicator() {
        return email_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setEmail_Indicator(int email_Indicator) {
        this.email_Indicator = email_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getStartDate_Indicator() {
        return startDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setStartDate_Indicator(int startDate_Indicator) {
        this.startDate_Indicator = startDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getEndDate_Indicator() {
        return endDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setEndDate_Indicator(int endDate_Indicator) {
        this.endDate_Indicator = endDate_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getAccountEnabled_Indicator() {
        return accountEnabled_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setAccountEnabled_Indicator(int accountEnabled_Indicator) {
        this.accountEnabled_Indicator = accountEnabled_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getAccountExpired_Indicator() {
        return accountExpired_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setAccountExpired_Indicator(int accountExpired_Indicator) {
        this.accountExpired_Indicator = accountExpired_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getAccountLocked_Indicator() {
        return accountLocked_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setAccountLocked_Indicator(int accountLocked_Indicator) {
        this.accountLocked_Indicator = accountLocked_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public int getCredentialsExpired_Indicator() {
        return credentialsExpired_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    public void setCredentialsExpired_Indicator(int credentialsExpired_Indicator) {
        this.credentialsExpired_Indicator = credentialsExpired_Indicator;
    }
}