package com.neteast.rmp.dao;

import com.neteast.rmp.dao.domain.RptColumnMeta;
import com.neteast.rmp.dao.domain.RptColumnMetaExample;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import java.util.List;

public interface RptColumnMetaDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    Integer insert(RptColumnMeta record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKey(RptColumnMeta record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeySelective(RptColumnMeta record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(RptColumnMetaExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(RptColumnMetaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    RptColumnMeta selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByExample(RptColumnMetaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int selectCountByExample(RptColumnMetaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(RptColumnMetaExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(RptColumnMetaExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_column_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeyForCgs(RptColumnMeta record);
}