package com.neteast.rmp.dao;

import com.neteast.rmp.dao.domain.RptMeta;
import com.neteast.rmp.dao.domain.RptMetaExample;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import java.util.List;

public interface RptMetaDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    Integer insert(RptMeta record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKey(RptMeta record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeySelective(RptMeta record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(RptMetaExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(RptMetaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    RptMeta selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByExample(RptMetaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int selectCountByExample(RptMetaExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(RptMetaExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(RptMetaExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_meta
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeyForCgs(RptMeta record);
}