package com.neteast.rmp.dao;

import com.neteast.rmp.dao.domain.RptTemplate;
import com.neteast.rmp.dao.domain.RptTemplateExample;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import java.util.List;

public interface RptTemplateDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    Integer insert(RptTemplate record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKey(RptTemplate record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeySelective(RptTemplate record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(RptTemplateExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(RptTemplateExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    RptTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByExample(RptTemplateExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int selectCountByExample(RptTemplateExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(RptTemplateExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(RptTemplateExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rpt_template
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeyForCgs(RptTemplate record);
}