package com.neteast.rmp.dao;

import com.neteast.rmp.dao.domain.ScCellCfg;
import com.neteast.rmp.dao.domain.ScCellCfgExample;
import com.neteast.rmp.dao.domain.ScCellCfgWithIdAndChildrenId;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import java.util.List;
import java.util.Map;

public interface ScCellCfgDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    Integer insert(ScCellCfg record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    int updateByPrimaryKey(ScCellCfg record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    int updateByPrimaryKeySelective(ScCellCfg record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    List selectByExample(ScCellCfgExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    List selectByExample(ScCellCfgExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    ScCellCfg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    int deleteByExample(ScCellCfgExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    int selectCountByExample(ScCellCfgExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    PageBox selectByExampleWithPaging(ScCellCfgExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    PageBox selectByExampleWithPaging(ScCellCfgExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_cfg
     *
     * @abatorgenerated Tue Apr 09 22:10:15 CST 2013
     */
    int updateByPrimaryKeyForCgs(ScCellCfg record);
    
    
    List<ScCellCfgWithIdAndChildrenId> selectIdAndChildrenId(String portalCode);

	public int editDescription(Map map);
    
}