package com.neteast.rmp.dao;

import com.neteast.rmp.dao.domain.ScCellParms;
import com.neteast.rmp.dao.domain.ScCellParmsExample;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import java.util.List;

public interface ScCellParmsDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    Integer insert(ScCellParms record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    int updateByPrimaryKey(ScCellParms record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    int updateByPrimaryKeySelective(ScCellParms record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    List selectByExample(ScCellParmsExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    List selectByExample(ScCellParmsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    ScCellParms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    int deleteByExample(ScCellParmsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    int selectCountByExample(ScCellParmsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    PageBox selectByExampleWithPaging(ScCellParmsExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    PageBox selectByExampleWithPaging(ScCellParmsExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_cell_parms
     *
     * @abatorgenerated Mon Apr 08 19:58:34 CST 2013
     */
    int updateByPrimaryKeyForCgs(ScCellParms record);
}