package com.neteast.rmp.dao;

import com.neteast.rmp.dao.domain.ScOrgSeq;
import com.neteast.rmp.dao.domain.ScOrgSeqExample;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import java.util.List;

public interface ScOrgSeqDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    void insert(ScOrgSeq record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    int updateByPrimaryKey(ScOrgSeq record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    int updateByPrimaryKeySelective(ScOrgSeq record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    List selectByExample(ScOrgSeqExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    List selectByExample(ScOrgSeqExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    ScOrgSeq selectByPrimaryKey(String orgCode);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    int deleteByExample(ScOrgSeqExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    int deleteByPrimaryKey(String orgCode);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    int selectCountByExample(ScOrgSeqExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    PageBox selectByExampleWithPaging(ScOrgSeqExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    PageBox selectByExampleWithPaging(ScOrgSeqExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org_seq
     *
     * @abatorgenerated Wed Oct 19 14:49:27 CST 2011
     */
    int updateByPrimaryKeyForCgs(ScOrgSeq record);
    int getNextOrgCurrSeq(String orgCode);
}