package com.neteast.rmp.dao;

import com.neteast.rmp.dao.domain.ScOrg;
import com.neteast.rmp.dao.domain.ScOrgExample;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import java.util.List;

public interface ScOrgDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    Integer insert(ScOrg record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKey(ScOrg record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeySelective(ScOrg record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(ScOrgExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(ScOrgExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    ScOrg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByExample(ScOrgExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int selectCountByExample(ScOrgExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(ScOrgExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(ScOrgExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_org
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeyForCgs(ScOrg record);
    
    List selectByCurrUserOrg(String orgCode);
}