package com.neteast.rmp.dao;

import java.util.List;
import java.util.Map;

import com.neteast.rmp.dao.domain.ScRoleMenu;
import com.neteast.rmp.dao.domain.ScRoleMenuExample;
import com.neteast.rmp.system.page.Criteria;
import com.seraph.bi.suite.support.domain.pagination.PageBox;

public interface ScRoleMenuDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    Integer insert(ScRoleMenu record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKey(ScRoleMenu record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeySelective(ScRoleMenu record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(ScRoleMenuExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(ScRoleMenuExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    ScRoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByExample(ScRoleMenuExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int selectCountByExample(ScRoleMenuExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(ScRoleMenuExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(ScRoleMenuExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeyForCgs(ScRoleMenu record);

	List getRoleMenuInfo(Criteria c);

	Integer getRoleMenuInfoCount(Criteria c);

	List getCheckedTreeNode(ScRoleMenuExample example);

	List<Map<String, Object>> getMenuIdsByIds(Map<String, Object> idMap);
}