package com.neteast.rmp.dao;

import com.neteast.rmp.dao.domain.ScRole;
import com.neteast.rmp.dao.domain.ScRoleExample;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import java.util.List;

public interface ScRoleDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    Integer insert(ScRole record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKey(ScRole record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeySelective(ScRole record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(ScRoleExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(ScRoleExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    ScRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByExample(ScRoleExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int selectCountByExample(ScRoleExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(ScRoleExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(ScRoleExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_role
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeyForCgs(ScRole record);
}