package com.neteast.rmp.dao;

import java.util.List;

import com.neteast.rmp.dao.domain.ScTreeMenu;
import com.neteast.rmp.dao.domain.ScTreeMenuExample;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import com.seraph.bi.suite.support.domain.tree.AsyncTreeNode;

public interface ScTreeMenuDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    Integer insert(ScTreeMenu record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKey(ScTreeMenu record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeySelective(ScTreeMenu record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(ScTreeMenuExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(ScTreeMenuExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    ScTreeMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByExample(ScTreeMenuExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int selectCountByExample(ScTreeMenuExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(ScTreeMenuExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(ScTreeMenuExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_tree_menu
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeyForCgs(ScTreeMenu record);
    
    List<AsyncTreeNode> selectLowerTreeMenuNodeByAuthorities(int menuId, String username);
    
}