package com.neteast.rmp.dao;

import com.neteast.rmp.dao.domain.ScUser;
import com.neteast.rmp.dao.domain.ScUserExample;
import com.seraph.bi.suite.support.domain.pagination.PageBox;
import java.util.List;

public interface ScUserDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    Integer insert(ScUser record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKey(ScUser record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeySelective(ScUser record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(ScUserExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    List selectByExample(ScUserExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    ScUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByExample(ScUserExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int selectCountByExample(ScUserExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(ScUserExample example, int pageSize, int pageNum, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    PageBox selectByExampleWithPaging(ScUserExample example, int pageSize, int pageNum);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table sc_user
     *
     * @abatorgenerated Tue Sep 20 22:24:44 CST 2011
     */
    int updateByPrimaryKeyForCgs(ScUser record);
}